<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSLLEventImageTable extends Doctrine_Table
{

    public function findImageReference( $itemId, $itemType )
    {
        $res = Doctrine_Query::create()->from( 'SLLEventImage i' )
                                       ->where( 'i.item_id = ? AND i.item_type = ?', array( $itemId, $itemType ) )
                                       ->execute();

        return count( $res ) > 0 ? $res[0] : false;
    }

    public function deleteImageReference( $itemId, $itemType )
    {
        $res = Doctrine_Query::create()->delete()
                                       ->from( 'SLLEventImage i' )
                                       ->where( 'i.item_id = ? AND i.item_type = ?', array( $itemId, $itemType ) )
                                       ->execute();

        return count( $res ) > 0 ? $res[0] : false;
    }


}