<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginSLLCategory extends BaseSLLCategory
{

    public function getSlug( )
    {
        return toToolkit::getAlias( $this->get( 'name' ) );
    }
}