<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginSLLEventImage extends BaseSLLEventImage
{
    public function setImageReference( $imageId )
    {
        return $this->_set( 'image_id', $imageId );
    }

}