<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSLLVenueCategoryInformationTable extends Doctrine_Table
{
    public function getVenueCategoryInformation( $venueId, $categoryId = false )
    {
        $q = $this->createQuery()->select('i.*, c.*')
                                 ->from( 'SLLVenueCategoryInformation i' )
                                 ->leftJoin( 'i.SLLCategory c ON i.category_id = c.id' )
                                 ->where( 'i.venue_id = ?', $venueId );

        $results = $q->execute();

        $aroundTownOverride = array();
        $eventCategoryOverride = array();

        foreach ( $results as $result )
        {
            if ( $result['SLLCategory']['name'] == 'Around Town' )
            {
            	$aroundTownOverride = $result->toArray();
            }

            if ( $result->category_id == $categoryId )
            {
                $eventCategoryOverride = $result->toArray();
            }
        }

        $default = array(   'annotation' => '',
                            'price_export' => '',
					        'telephone_export' => '',
					        'times_export' => '',
					        'url_export' => '',
					        'food_served' => '',
					        'free_venue' => '',
					        'late_night' => '' );

        // Array overrides from right to left:
        $venueCategoryInfo = array_merge( $default, $aroundTownOverride, $eventCategoryOverride );

        return $venueCategoryInfo;
    }
}