<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../lib/import/ny/nyImport.class.php';
require_once dirname(__FILE__).'/../../../../../lib/processCsv.class.php';
require_once dirname(__FILE__).'/../../../../../test/bootstrap/unit.php';
spl_autoload_register(array('Doctrine', 'autoload'));


/**
 * Test class for importNyED.
 * Generated by PHPUnit on 2010-01-18 at 15:44:47.
 *
 * @author Ralph Schwaninger <ralphschwaninger@timeout.com>
 *
 */
class importNyEDTest extends PHPUnit_Framework_TestCase {

  /**
   * @var importNyED
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    try {

      $pDB = Doctrine_Manager::connection(new PDO('sqlite::memory:'));
      Doctrine::createTablesFromModels( dirname(__FILE__).'/../../../../../lib/model/doctrine');
    }
    catch(PDOException $e)
    {
      echo $e->getMessage();
    }

    $vendor = new Vendor();
    $vendor->setCity('test');
    $vendor->setLanguage('english');
    $vendor->save();
    $vendor;

    $category = new PoiCategory();
    $category->setName( 'restaurant' );
    $category->save();
    
    $csv = new processCsv( dirname( __FILE__ ) . '/../../../data/tony_ed_test.csv' );

    $this->object = new importNyED( $csv, $vendor );
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    Doctrine_Manager::getInstance()->closeConnection(Doctrine_Manager::connection());
  }

  /**
   * testInsertPois().
   */
  public function testInsertPois() {
    
    $this->assertTrue( $this->object->insertPois() );
  }

  /**
   * testInsertPoiWithCompleteData().
   */
  /*public function testInsertPoiWithCompleteData() {
    
    $category = new PoiCategory();
    $category->setName( 'test' );
    $category->save();

    $data[ 'name' ] = 'The test restaurant';
    $data[ 'review' ] = 'This is a review text...';
    $data[ 'address' ] = '45th Avenue';
    $data[ 'city' ] = 'New York';
    $data[ 'area' ] = 'Manhattan';
    $data[ 'directions' ] = 'just up the road';

    $data[ 'latitude' ] = '0.1';
    $data[ 'longitude' ] = '0.2';

    $data[ 'phone' ] = '+123';
    $data[ 'opening_hours' ] = '9-5';
    $data[ 'website' ] = 'supercool.com';
    $data[ 'Vendor' ] = 1;
    $data[ 'PoiCategory' ] = 1;

    $this->assertTrue( $this->object->insertPoi( $data ) );
  }*/

    /**
   * testInsertPoiWithCompleteData().
   */
  /*public function testInsertPoiWithIncompleteData() {

    $category = new PoiCategory();
    $category->setName( 'test' );
    $category->save();

    $data[ 'phone' ] = '+123';
    $data[ 'opening_hours' ] = '9-5';
    $data[ 'website' ] = 'supercool.com';
    $data[ 'Vendor' ] = 1;
    $data[ 'PoiCategory' ] = 1;    
    
    $this->assertTrue( $this->object->insertPoi( $data ) instanceof Doctrine_Exception );

  }*/


}
?>
