<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../lib/processXml.class.php';
require_once dirname(__FILE__).'/../../../../../lib/import/ny/processNyBcXml.class.php';
require_once dirname(__FILE__).'/../../../../../test/bootstrap/unit.php';
require_once dirname( __FILE__ ) . '/../../../bootstrap.php';
spl_autoload_register(array('Doctrine', 'autoload'));


/**
 * Test class for nyImportBcclass.
 * Generated by PHPUnit on 2010-02-12 at 10:52:15.
 */
class nyImportBcXmlTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var nyImportBcclass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
         try {

          ProjectN_Test_Unit_Factory::createDatabases();

          Doctrine::loadData('data/fixtures');
          $this->vendorObj = Doctrine::getTable('Vendor')->getVendorByCityAndLanguage('ny', 'en-US');

          $this->xmlObj = new processNyBcXml( dirname(__FILE__).'/../../../data/tony_bc.xml' );
          
        }
        catch( Exception $e )
        {
          echo $e->getMessage();
        }

      //  $this->object = new processNyBcXml($this->xmlObj, $this->vendorObj );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


    /**
     * @todo finish the function
     */
    public function testImportBars()
    {

        //$this->object->importBars();
        //$this->assertTrue(true);
    }
}
?>
