<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../lib/processXml.class.php';
require_once dirname(__FILE__).'/../../../../../lib/import/ny/processNyBcXml.class.php';



/**
 * Test class for processNyBcXml.
 * Generated by PHPUnit on 2010-02-12 at 12:50:29.
 */
class processNyBcXmlTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var processNyBcXml
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new processNyBcXml(dirname(__FILE__).'/../../../data/tony_bc.xml');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSetPoi().
     */
    public function testXmlIsSet()
    {
 
       $this->assertTrue($this->object->xmlObj instanceof SimpleXMLElement, 'Test that its a simple Xml object');
    }
}
?>
