<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../lib/processXml.class.php';
require_once dirname(__FILE__).'/../../../../../lib/import/ny/processNyXml.php';

/**
 * Test class for processNyXml.
 * Generated by PHPUnit on 2010-01-14 at 13:10:31.
 */
class processNyXmlTest extends PHPUnit_Framework_TestCase {
  /**
   * @var processNyXml
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new processNyXml(dirname(__FILE__).'/../../../data/tony_leo_test_correct.xml');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
  * Test that the events are loaded
  */
  public function testSettingAndGettingEvents()
  {
    $this->object->setEvents('/body/event');
    $this->assertType('array', $this->object->getEvents());
  }


  /**
  * Test that the venues are loaded
  */
  public function testSettingAndGettingVenues()
  {
    $this->object->setVenues('/body/address');
    $this->assertType('array', $this->object->getVenues());
  }

}
?>
