<?php
require_once 'PHPUnit/Framework.php';
require_once dirname(__FILE__).'/../../bootstrap/unit.php';
require_once dirname(__FILE__).'/../bootstrap.php';

/**
 * Test class for FTPClient.
 * Generated by PHPUnit on 2010-02-04 at 16:48:16.
 */
class FTPClientTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var FTPClient
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new FTPClient( 'ftp.timeoutny.com', 'london', 'timeout' );
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    unset( $this->object );
  }

  /**
   * @todo use a mock?
   */
  public function testFetchAll()
  {
    //$this->object->fetchDirContents( '/NOKIA', TO_TEST_DATA_PATH . '/downloaded_feeds/ny' );
  }

  /**
   * @todo use a mock?
   */
  public function testFetchFile()
  {
    //$this->object->fetchFile( '/NOKIA/tony_bc.xml', TO_TEST_DATA_PATH . '/downloaded_feeds/ny/test.file' );
  }
}
?>
