<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../lib/processXml.class.php';

/**
 * Test class for processXml.
 * Generated by PHPUnit on 2010-01-05 at 17:11:37.
 */
class processXmlTest extends PHPUnit_Framework_TestCase {
    /**
     * @var processXml
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
      
    }


    /**
     * Test that the xml file passed in exists and is loaded
     */
    public function testXmlFileIsLoaded()
    {
      $this->object = new processXml(dirname(__FILE__).'/../data/tony_leo_test_correct.xml');
      $this->assertType('object', $this->object->getXml());
    }


    /**
     * Test that a file is handled if it doesn't exist
     */
    public function testXmlFileNotLoaded()
    {
      $this->object = new processXml(dirname(__FILE__).'/../data/tony_leo_test_INcorrect.xml');

      $this->assertFalse($this->object->getXml());
    }
}
?>
