<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../lib/Curl.class.php';
require_once dirname(__FILE__).'/../../../lib/reverseGeocode.class.php';

/**
 * Test class for reverseGeocode.
 * Generated by PHPUnit on 2010-02-10 at 16:43:45.
 */
class reverseGeocodeTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var reverseGeocode
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new reverseGeocode( 501.52059, -0.13479 );
  }

  /**
   * @todo Implement testGetAddresses().
   */
  public function testGetAddresses()
  {
    $this->assertTrue( $this->object->getAddressesXml() instanceof SimpleXMLElement );
  }
}
?>
