<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ImportLogger', 'project_n');

/**
 * BaseImportLogger
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $total_inserts
 * @property integer $total_updates
 * @property integer $vendor_id
 * @property enum $type
 * @property time $total_time
 * @property Vendor $Vendor
 * @property Doctrine_Collection $ImportLoggerChanges
 * @property Doctrine_Collection $ImportLoggerErrors
 * 
 * @method integer             getTotalInserts()        Returns the current record's "total_inserts" value
 * @method integer             getTotalUpdates()        Returns the current record's "total_updates" value
 * @method integer             getVendorId()            Returns the current record's "vendor_id" value
 * @method enum                getType()                Returns the current record's "type" value
 * @method time                getTotalTime()           Returns the current record's "total_time" value
 * @method Vendor              getVendor()              Returns the current record's "Vendor" value
 * @method Doctrine_Collection getImportLoggerChanges() Returns the current record's "ImportLoggerChanges" collection
 * @method Doctrine_Collection getImportLoggerErrors()  Returns the current record's "ImportLoggerErrors" collection
 * @method ImportLogger        setTotalInserts()        Sets the current record's "total_inserts" value
 * @method ImportLogger        setTotalUpdates()        Sets the current record's "total_updates" value
 * @method ImportLogger        setVendorId()            Sets the current record's "vendor_id" value
 * @method ImportLogger        setType()                Sets the current record's "type" value
 * @method ImportLogger        setTotalTime()           Sets the current record's "total_time" value
 * @method ImportLogger        setVendor()              Sets the current record's "Vendor" value
 * @method ImportLogger        setImportLoggerChanges() Sets the current record's "ImportLoggerChanges" collection
 * @method ImportLogger        setImportLoggerErrors()  Sets the current record's "ImportLoggerErrors" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseImportLogger extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('import_logger');
        $this->hasColumn('total_inserts', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('total_updates', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('vendor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'movie',
              1 => 'poi',
              2 => 'event',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('total_time', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vendor', array(
             'local' => 'vendor_id',
             'foreign' => 'id'));

        $this->hasMany('ImportLoggerChange as ImportLoggerChanges', array(
             'local' => 'id',
             'foreign' => 'import_logger_id'));

        $this->hasMany('ImportLoggerError as ImportLoggerErrors', array(
             'local' => 'id',
             'foreign' => 'import_logger_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}