<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LinkingEventCategoryMapping', 'project_n');

/**
 * BaseLinkingEventCategoryMapping
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $event_category_id
 * @property integer $vendor_event_category_id
 * 
 * @method integer                     getEventCategoryId()          Returns the current record's "event_category_id" value
 * @method integer                     getVendorEventCategoryId()    Returns the current record's "vendor_event_category_id" value
 * @method LinkingEventCategoryMapping setEventCategoryId()          Sets the current record's "event_category_id" value
 * @method LinkingEventCategoryMapping setVendorEventCategoryId()    Sets the current record's "vendor_event_category_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLinkingEventCategoryMapping extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('linking_event_category_mapping');
        $this->hasColumn('event_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('vendor_event_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}