<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OverrideEvent', 'project_n');

/**
 * BaseOverrideEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $override_id
 * @property integer $event_id
 * 
 * @method integer       getOverrideId()  Returns the current record's "override_id" value
 * @method integer       getEventId()     Returns the current record's "event_id" value
 * @method OverrideEvent setOverrideId()  Sets the current record's "override_id" value
 * @method OverrideEvent setEventId()     Sets the current record's "event_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseOverrideEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('override_event');
        $this->hasColumn('override_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}