<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ImportLoggerError', 'project_n');

/**
 * BaseImportLoggerError
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $trace
 * @property string $log
 * @property string $type
 * @property string $message
 * @property string $serialized_object
 * @property integer $import_logger_id
 * @property boolean $resolved
 * @property ImportLogger $ImportLogger
 * 
 * @method string            getTrace()             Returns the current record's "trace" value
 * @method string            getLog()               Returns the current record's "log" value
 * @method string            getType()              Returns the current record's "type" value
 * @method string            getMessage()           Returns the current record's "message" value
 * @method string            getSerializedObject()  Returns the current record's "serialized_object" value
 * @method integer           getImportLoggerId()    Returns the current record's "import_logger_id" value
 * @method boolean           getResolved()          Returns the current record's "resolved" value
 * @method ImportLogger      getImportLogger()      Returns the current record's "ImportLogger" value
 * @method ImportLoggerError setTrace()             Sets the current record's "trace" value
 * @method ImportLoggerError setLog()               Sets the current record's "log" value
 * @method ImportLoggerError setType()              Sets the current record's "type" value
 * @method ImportLoggerError setMessage()           Sets the current record's "message" value
 * @method ImportLoggerError setSerializedObject()  Sets the current record's "serialized_object" value
 * @method ImportLoggerError setImportLoggerId()    Sets the current record's "import_logger_id" value
 * @method ImportLoggerError setResolved()          Sets the current record's "resolved" value
 * @method ImportLoggerError setImportLogger()      Sets the current record's "ImportLogger" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseImportLoggerError extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('import_logger_error');
        $this->hasColumn('trace', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('log', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('serialized_object', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('import_logger_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('resolved', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ImportLogger', array(
             'local' => 'import_logger_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}