<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VendorEventCategory', 'project_n');

/**
 * BaseVendorEventCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $vendor_id
 * @property Vendor $Vendor
 * @property Doctrine_Collection $Event
 * @property Doctrine_Collection $EventCategory
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method integer             getVendorId()      Returns the current record's "vendor_id" value
 * @method Vendor              getVendor()        Returns the current record's "Vendor" value
 * @method Doctrine_Collection getEvent()         Returns the current record's "Event" collection
 * @method Doctrine_Collection getEventCategory() Returns the current record's "EventCategory" collection
 * @method VendorEventCategory setName()          Sets the current record's "name" value
 * @method VendorEventCategory setVendorId()      Sets the current record's "vendor_id" value
 * @method VendorEventCategory setVendor()        Sets the current record's "Vendor" value
 * @method VendorEventCategory setEvent()         Sets the current record's "Event" collection
 * @method VendorEventCategory setEventCategory() Sets the current record's "EventCategory" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVendorEventCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vendor_event_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('vendor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('name_index', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vendor', array(
             'local' => 'vendor_id',
             'foreign' => 'id'));

        $this->hasMany('Event', array(
             'refClass' => 'LinkingVendorEventCategory',
             'local' => 'vendor_event_category_id',
             'foreign' => 'event_id'));

        $this->hasMany('EventCategory', array(
             'refClass' => 'LinkingEventCategoryMapping',
             'local' => 'vendor_event_category_id',
             'foreign' => 'event_category_id'));
    }
}