<?php

/**
 * BasePoiParentCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Poi
 * @property Doctrine_Collection $PoiParentCategory
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method Doctrine_Collection getPoi()               Returns the current record's "Poi" collection
 * @method Doctrine_Collection getPoiParentCategory() Returns the current record's "PoiParentCategory" collection
 * @method PoiParentCategory   setName()              Sets the current record's "name" value
 * @method PoiParentCategory   setPoi()               Sets the current record's "Poi" collection
 * @method PoiParentCategory   setPoiParentCategory() Sets the current record's "PoiParentCategory" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePoiParentCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poi_parent_category');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Poi', array(
             'local' => 'id',
             'foreign' => 'poi_parent_category_id'));

        $this->hasMany('PoiCategory as PoiParentCategory', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}