<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Logger', 'project_n');

/**
 * BaseLogger
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vendor_id
 * @property enum $status
 * @property time $total_time
 * @property Vendor $Vendor
 * 
 * @method integer getVendorId()   Returns the current record's "vendor_id" value
 * @method enum    getStatus()     Returns the current record's "status" value
 * @method time    getTotalTime()  Returns the current record's "total_time" value
 * @method Vendor  getVendor()     Returns the current record's "Vendor" value
 * @method Logger  setVendorId()   Sets the current record's "vendor_id" value
 * @method Logger  setStatus()     Sets the current record's "status" value
 * @method Logger  setTotalTime()  Sets the current record's "total_time" value
 * @method Logger  setVendor()     Sets the current record's "Vendor" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLogger extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('logger');
        $this->hasColumn('vendor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'running',
              1 => 'failed',
              2 => 'success',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('total_time', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));


        $this->index('status_index', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vendor', array(
             'local' => 'vendor_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}