<?php

/**
 * BaseMovieGenres
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $movie_id
 * @property integer $genre_id
 * @property Movie $Movie
 * @property MovieGenre $MovieGenre
 * 
 * @method integer     getMovieId()    Returns the current record's "movie_id" value
 * @method integer     getGenreId()    Returns the current record's "genre_id" value
 * @method Movie       getMovie()      Returns the current record's "Movie" value
 * @method MovieGenre  getMovieGenre() Returns the current record's "MovieGenre" value
 * @method MovieGenres setMovieId()    Sets the current record's "movie_id" value
 * @method MovieGenres setGenreId()    Sets the current record's "genre_id" value
 * @method MovieGenres setMovie()      Sets the current record's "Movie" value
 * @method MovieGenres setMovieGenre() Sets the current record's "MovieGenre" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMovieGenres extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('movie_genres');
        $this->hasColumn('movie_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('genre_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Movie', array(
             'local' => 'movie_id',
             'foreign' => 'id'));

        $this->hasOne('MovieGenre', array(
             'local' => 'genre_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}