<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OverridePoi', 'project_n');

/**
 * BaseOverridePoi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $override_id
 * @property integer $poi_id
 * 
 * @method integer     getOverrideId()  Returns the current record's "override_id" value
 * @method integer     getPoiId()       Returns the current record's "poi_id" value
 * @method OverridePoi setOverrideId()  Sets the current record's "override_id" value
 * @method OverridePoi setPoiId()       Sets the current record's "poi_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseOverridePoi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('override_poi');
        $this->hasColumn('override_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('poi_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}