<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RecordFieldOverrideEvent', 'project_n');

/**
 * BaseRecordFieldOverrideEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Event $Event
 * 
 * @method Event                    getEvent() Returns the current record's "Event" value
 * @method RecordFieldOverrideEvent setEvent() Sets the current record's "Event" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRecordFieldOverrideEvent extends RecordFieldOverride
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('record_field_override_event');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'record_id',
             'foreign' => 'id'));
    }
}