<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExportRecordLogger', 'project_n');

/**
 * BaseExportRecordLogger
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vendor_record_id
 * @property integer $export_logger_id
 * @property ExportLogger $ExportLogger
 * 
 * @method integer            getVendorRecordId()   Returns the current record's "vendor_record_id" value
 * @method integer            getExportLoggerId()   Returns the current record's "export_logger_id" value
 * @method ExportLogger       getExportLogger()     Returns the current record's "ExportLogger" value
 * @method ExportRecordLogger setVendorRecordId()   Sets the current record's "vendor_record_id" value
 * @method ExportRecordLogger setExportLoggerId()   Sets the current record's "export_logger_id" value
 * @method ExportRecordLogger setExportLogger()     Sets the current record's "ExportLogger" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseExportRecordLogger extends Logger
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('export_record_logger');
        $this->hasColumn('vendor_record_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('export_logger_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('vendor_record_id_index', array(
             'fields' => 
             array(
              0 => 'vendor_record_id',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExportLogger', array(
             'local' => 'export_logger_id',
             'foreign' => 'id'));
    }
}