<?php

/**
 * BasePoiUserContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $vender_ucid
 * @property string $comment_subject
 * @property string $comment_body
 * @property float $user_rating
 * @property integer $poi_user_id
 * @property integer $poi_id
 * @property PoiUser $PoiUser
 * @property Poi $Poi
 * 
 * @method string         getVenderUcid()      Returns the current record's "vender_ucid" value
 * @method string         getCommentSubject()  Returns the current record's "comment_subject" value
 * @method string         getCommentBody()     Returns the current record's "comment_body" value
 * @method float          getUserRating()      Returns the current record's "user_rating" value
 * @method integer        getPoiUserId()       Returns the current record's "poi_user_id" value
 * @method integer        getPoiId()           Returns the current record's "poi_id" value
 * @method PoiUser        getPoiUser()         Returns the current record's "PoiUser" value
 * @method Poi            getPoi()             Returns the current record's "Poi" value
 * @method PoiUserContent setVenderUcid()      Sets the current record's "vender_ucid" value
 * @method PoiUserContent setCommentSubject()  Sets the current record's "comment_subject" value
 * @method PoiUserContent setCommentBody()     Sets the current record's "comment_body" value
 * @method PoiUserContent setUserRating()      Sets the current record's "user_rating" value
 * @method PoiUserContent setPoiUserId()       Sets the current record's "poi_user_id" value
 * @method PoiUserContent setPoiId()           Sets the current record's "poi_id" value
 * @method PoiUserContent setPoiUser()         Sets the current record's "PoiUser" value
 * @method PoiUserContent setPoi()             Sets the current record's "Poi" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePoiUserContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poi_user_content');
        $this->hasColumn('vender_ucid', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '32',
             ));
        $this->hasColumn('comment_subject', 'string', 512, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '512',
             ));
        $this->hasColumn('comment_body', 'string', 65535, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '65535',
             ));
        $this->hasColumn('user_rating', 'float', null, array(
             'type' => 'float',
             'notnull' => false,
             ));
        $this->hasColumn('poi_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('poi_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PoiUser', array(
             'local' => 'poi_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Poi', array(
             'local' => 'poi_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}