<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EventCategory', 'project_n');

/**
 * BaseEventCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Event
 * @property Doctrine_Collection $VendorEventCategory
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method Doctrine_Collection getEvent()               Returns the current record's "Event" collection
 * @method Doctrine_Collection getVendorEventCategory() Returns the current record's "VendorEventCategory" collection
 * @method EventCategory       setName()                Sets the current record's "name" value
 * @method EventCategory       setEvent()               Sets the current record's "Event" collection
 * @method EventCategory       setVendorEventCategory() Sets the current record's "VendorEventCategory" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseEventCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_category');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));


        $this->index('name_index', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Event', array(
             'refClass' => 'LinkingEventCategory',
             'local' => 'event_category_id',
             'foreign' => 'event_id'));

        $this->hasMany('VendorEventCategory', array(
             'refClass' => 'LinkingEventCategoryMapping',
             'local' => 'event_category_id',
             'foreign' => 'vendor_event_category_id'));
    }
}