<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LinkingPoiCategoryMapping', 'project_n');

/**
 * BaseLinkingPoiCategoryMapping
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $poi_category_id
 * @property integer $vendor_poi_category_id
 * 
 * @method integer                   getPoiCategoryId()          Returns the current record's "poi_category_id" value
 * @method integer                   getVendorPoiCategoryId()    Returns the current record's "vendor_poi_category_id" value
 * @method LinkingPoiCategoryMapping setPoiCategoryId()          Sets the current record's "poi_category_id" value
 * @method LinkingPoiCategoryMapping setVendorPoiCategoryId()    Sets the current record's "vendor_poi_category_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLinkingPoiCategoryMapping extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('linking_poi_category_mapping');
        $this->hasColumn('poi_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('vendor_poi_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}