<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LinkingImportLoggerSuccessEvent', 'project_n');

/**
 * BaseLinkingImportLoggerSuccessEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $import_logger_success_id
 * @property integer $event_id
 * 
 * @method integer                         getImportLoggerSuccessId()    Returns the current record's "import_logger_success_id" value
 * @method integer                         getEventId()                  Returns the current record's "event_id" value
 * @method LinkingImportLoggerSuccessEvent setImportLoggerSuccessId()    Sets the current record's "import_logger_success_id" value
 * @method LinkingImportLoggerSuccessEvent setEventId()                  Sets the current record's "event_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLinkingImportLoggerSuccessEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('linking_import_logger_success_event');
        $this->hasColumn('import_logger_success_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}