<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExportLogger', 'project_n');

/**
 * BaseExportLogger
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $ExportRecordLogger
 * @property Doctrine_Collection $ExportSkippedRecordLogger
 * 
 * @method Doctrine_Collection getExportRecordLogger()        Returns the current record's "ExportRecordLogger" collection
 * @method Doctrine_Collection getExportSkippedRecordLogger() Returns the current record's "ExportSkippedRecordLogger" collection
 * @method ExportLogger        setExportRecordLogger()        Sets the current record's "ExportRecordLogger" collection
 * @method ExportLogger        setExportSkippedRecordLogger() Sets the current record's "ExportSkippedRecordLogger" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseExportLogger extends Logger
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('export_logger');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ExportRecordLogger', array(
             'local' => 'id',
             'foreign' => 'export_logger_id'));

        $this->hasMany('ExportSkippedRecordLogger', array(
             'local' => 'id',
             'foreign' => 'export_logger_id'));
    }
}