<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExportSkippedRecordLogger', 'project_n');

/**
 * BaseExportSkippedRecordLogger
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $record_id
 * @property string $model
 * @property integer $vendor_record_id
 * @property string $log
 * @property integer $export_logger_id
 * @property ExportLogger $ExportLogger
 * 
 * @method integer                   getRecordId()         Returns the current record's "record_id" value
 * @method string                    getModel()            Returns the current record's "model" value
 * @method integer                   getVendorRecordId()   Returns the current record's "vendor_record_id" value
 * @method string                    getLog()              Returns the current record's "log" value
 * @method integer                   getExportLoggerId()   Returns the current record's "export_logger_id" value
 * @method ExportLogger              getExportLogger()     Returns the current record's "ExportLogger" value
 * @method ExportSkippedRecordLogger setRecordId()         Sets the current record's "record_id" value
 * @method ExportSkippedRecordLogger setModel()            Sets the current record's "model" value
 * @method ExportSkippedRecordLogger setVendorRecordId()   Sets the current record's "vendor_record_id" value
 * @method ExportSkippedRecordLogger setLog()              Sets the current record's "log" value
 * @method ExportSkippedRecordLogger setExportLoggerId()   Sets the current record's "export_logger_id" value
 * @method ExportSkippedRecordLogger setExportLogger()     Sets the current record's "ExportLogger" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseExportSkippedRecordLogger extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('export_skipped_record_logger');
        $this->hasColumn('record_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('model', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('vendor_record_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('log', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('export_logger_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('record_id_index', array(
             'fields' => 
             array(
              0 => 'record_id',
             ),
             ));
        $this->index('model_index', array(
             'fields' => 
             array(
              0 => 'model',
             ),
             ));
        $this->index('vendor_record_id_index', array(
             'fields' => 
             array(
              0 => 'vendor_record_id',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExportLogger', array(
             'local' => 'export_logger_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}