<?php

/**
 * BasePoiUpdatesLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePoiUpdatesLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poi_updates_log');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}