<?php

/**
 * BaseVendor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $city
 * @property string $language
 * @property Doctrine_Collection $Poi
 * @property Doctrine_Collection $User
 * @property Doctrine_Collection $Event
 * @property Doctrine_Collection $Movie
 * 
 * @method string              getCity()     Returns the current record's "city" value
 * @method string              getLanguage() Returns the current record's "language" value
 * @method Doctrine_Collection getPoi()      Returns the current record's "Poi" collection
 * @method Doctrine_Collection getUser()     Returns the current record's "User" collection
 * @method Doctrine_Collection getEvent()    Returns the current record's "Event" collection
 * @method Doctrine_Collection getMovie()    Returns the current record's "Movie" collection
 * @method Vendor              setCity()     Sets the current record's "city" value
 * @method Vendor              setLanguage() Sets the current record's "language" value
 * @method Vendor              setPoi()      Sets the current record's "Poi" collection
 * @method Vendor              setUser()     Sets the current record's "User" collection
 * @method Vendor              setEvent()    Sets the current record's "Event" collection
 * @method Vendor              setMovie()    Sets the current record's "Movie" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVendor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vendor');
        $this->hasColumn('city', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '15',
             ));
        $this->hasColumn('language', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Poi', array(
             'local' => 'id',
             'foreign' => 'vendor_id'));

        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'vendor_id'));

        $this->hasMany('Event', array(
             'local' => 'id',
             'foreign' => 'vendor_id'));

        $this->hasMany('Movie', array(
             'local' => 'id',
             'foreign' => 'vendor_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}