<?php

/**
 * BasePoiCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parent_id
 * @property string $name
 * @property PoiCategory $Parent
 * @property Doctrine_Collection $Poi
 * @property Doctrine_Collection $SubCategories
 * 
 * @method integer             getParentId()      Returns the current record's "parent_id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method PoiCategory         getParent()        Returns the current record's "Parent" value
 * @method Doctrine_Collection getPoi()           Returns the current record's "Poi" collection
 * @method Doctrine_Collection getSubCategories() Returns the current record's "SubCategories" collection
 * @method PoiCategory         setParentId()      Sets the current record's "parent_id" value
 * @method PoiCategory         setName()          Sets the current record's "name" value
 * @method PoiCategory         setParent()        Sets the current record's "Parent" value
 * @method PoiCategory         setPoi()           Sets the current record's "Poi" collection
 * @method PoiCategory         setSubCategories() Sets the current record's "SubCategories" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePoiCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poi_category');
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PoiCategory as Parent', array(
             'local' => 'parent_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Poi', array(
             'local' => 'id',
             'foreign' => 'poi_category_id'));

        $this->hasMany('PoiCategory as SubCategories', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}