<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LinkingMovieGenre', 'project_n');

/**
 * BaseLinkingMovieGenre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $movie_genre_id
 * @property integer $movie_id
 * 
 * @method integer           getMovieGenreId()   Returns the current record's "movie_genre_id" value
 * @method integer           getMovieId()        Returns the current record's "movie_id" value
 * @method LinkingMovieGenre setMovieGenreId()   Sets the current record's "movie_genre_id" value
 * @method LinkingMovieGenre setMovieId()        Sets the current record's "movie_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLinkingMovieGenre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('linking_movie_genre');
        $this->hasColumn('movie_genre_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('movie_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}