generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Poi
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          poi
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        DuplicatePoisForm: { label: "Duplicate Poi's" }
        UnsolvableForm:    { label: 'Unsolvable POI?' }
        hide_unsolvable: { label: 'Hide Unsolvable' }
      list:
        display: [ poi_name, longitude, latitude, city, _duplicate]
        object_actions:
          _edit: ~
        actions: {}
        batch_actions: {}
      filter:
          class: PoiBackendFormFilter
          display:
            - filter_by
            - hide_unsolvable
            - id
            - vendor_id
            - vendor_poi_id
            - poi_name
            - street
            - city
            - zips
            - longitude
            - latitude
            - geocode_look_up
            - district
            - country
            - additional_address_details
            - short_description
            - description
            - poi_category_list
            - vendor_poi_category_list
            - email
            - url
            - phone
            - phone2
            - fax
            - keywords
            - public_transport_links
            - price_information
            - openingtimes
            - star_rating
            - rating
            - provider
            - local_language
            - review_date
            - created_at
            - updated_at
      form:
        class: PoiBackendForm
        actions: { _list: ~, _save: ~ }
      edit:
        display:
          Editable:
            - DuplicatePoisForm
            - poi_name
            - house_no
            - street
            - city
            - district
            - country
            - additional_address_details
            - zips
            - longitude
            - latitude
            - email
            - url
            - phone
            - phone2
            - fax
            - keywords
            - short_description
            - description
            - public_transport_links
            - price_information
            - openingtimes
            - star_rating
            - rating
            - provider
            - poi_category_list
            - vendor_poi_category_list
            - UnsolvableForm
          Info:
            - vendor_poi_id
            - review_date
            - local_language
            - id
            - created_at
            - updated_at
            - vendor_id
            #- vendor_category
            - geocode_look_up
      new:
        display:
          Editable:
            - poi_name
            - house_no
            - street
            - city
            - district
            - country
            - additional_address_details
            - zips
            - longitude
            - latitude
            - email
            - url
            - phone
            - phone2
            - fax
            - keywords
            - short_description
            - description
            - public_transport_links
            - price_information
            - openingtimes
            - star_rating
            - rating
            - provider
            - poi_category_list
            - vendor_poi_category_list
            - UnsolvableForm
          Info:
            - vendor_poi_id
            - review_date
            - local_language
            - id
            - created_at
            - updated_at
            - vendor_id
            #- vendor_category
            - geocode_look_up
