generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Poi
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          poi
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, longitude, latitude, city]
        object_actions:
          _edit: ~
        actions: {}
        batch_actions: {}
      filter:
          class: PoiBackendFormFilter
          display:
            - id
            - vendor_id
            - vendor_poi_id
            - poi_name
            - street
            - city
            - zips
            - longitude
            - latitude
            - geocode_look_up
            - district
            - country
            - additional_address_details
            - short_description
            - description
            - poi_category_list
            - vendor_poi_category_list
            - email
            - url
            - phone
            - phone2
            - fax
            - keywords
            - public_transport_links
            - price_information
            - openingtimes
            - star_rating
            - rating
            - provider
            - local_language
            - review_date
            - created_at
            - updated_at
      form:
        actions: { _list: ~, _save: ~ }
        display:
          Editable:
            - poi_name
            - house_no
            - street
            - city
            - district
            - country
            - additional_address_details
            - zips
            - longitude
            - latitude
            - email
            - url
            - phone
            - phone2
            - fax
            - keywords
            - short_description
            - description
            - public_transport_links
            - price_information
            - openingtimes
            - star_rating
            - rating
            - provider
            - poi_category_list
            - vendor_poi_category_list
          Info: 
            - vendor_poi_id
            - review_date
            - local_language
            - id
            - created_at
            - updated_at
            - vendor_id
            #- vendor_category
            - geocode_look_up
      edit:    ~
      new:     ~
