# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  #matches url: http://projectn.local/
  data_entry:
#.....................................................................
#     Data entry mappers are used for two different cases:
#     1 : importing from data entry database:
#         - in this case, onUpdateFindById is FALSE and vpid field in the input XML is interpreted as   vendor_event_id
#     2 : updating data_entry database
#         - steps for update :
#            * in projectn installation, we ran an export to create the XML files
#            * for some cities, the runner configuration has exportForDataEntry: true value, for those cities, prepareExportXMLsForDataEntryTask is called to create
#              new XML files with the modified IDs
#         - in data_entry instance the modified XML files are used to import the data back to data_entry database ,in this case, app_data_entry_onUpdateFindById is
#              TRUE and vpid field in the input XML is interpreted as the ID of the poi to be updated
#.......................................................................
    onUpdateFindById: false
  runner:
    order: [ import, export ]
  import:
    cities:
#        -
#          name: singapore
#          type: [ poi-event, movie ]
#
#        -
#          name: singapore
#          language: en-US
#          type:
#            poi-event:
#              
#              mapperParams:
#                poi_url: http://www.timeoutsingapore.com/xmlapi/venues/
#                section: index
#                full:
#                key: ffab6a24c60f562ecf705130a36c1d1e
#            movie:
#              language: en-US
#              mapperParams:
#                url: http://www.timeoutsingapore.com/xmlapi/movies/
#                section: index
#                full:
#                key: ffab6a24c60f562ecf705130a36c1d1e
              
#        -
#          name: nyfix
#          type: [ fixid ]
#        -
#          name: ny
#          type: [ poi-event, eating-drinking, bars-clubs, movie ]
#        -
#          name: chicago
#          type: [ poi, poi-bc, poi-ed, event, movie]   
        -
          name: chicago
          language: en-US
          ftp:
            host: ftp.timeoutchicago.com
            user: timeout
            password: y6fv2LS8
          type:
            poi-bc:
              mapper:
                class: ChicagoFeedBCMapper
                params:
                  file_name: toc_bc.xml
            poi-ed:
              mapper:
                class: ChicagoFeedEDMapper
                params:
                  file_name: toc_ed.xml
            poi:
              mapper:
                class: ChicagoFeedPoiMapper
                params:
                  file_name: toc_leo.xml
            event:
              mapper:
                class: ChicagoFeedEventMapper
                params:
                  file_name: toc_leo.xml
            movie:
              mapper:
                class: londonDatabaseFilmsDataMapper

        -
          name: london
          language: en-GB
          type:
            poi-ev-mapper:
              mapper:
                class: LondonDatabaseEventsAndVenuesMapper
                params:
                  type: poi
            poi-bars-pubs:
              mapper:
                class: LondonAPIBarsAndPubsMapper
                params:
                  datasource:
                    classname: LondonAPICrawler
                    url: http://api.timeout.com/v1/search.xml
                    detailedurl: http://api.timeout.com/v1/getBar.xml
                    apitype: Bars & pubs
            poi-restaurant:
              class: LondonAPIRestaurantsMapper
            poi-cinemas:
              class: LondonAPICinemasMapper
            event:
              class: LondonDatabaseEventsAndVenuesMapper
              params:
                type: event
            event-occurrence:
              class: LondonDatabaseEventsAndVenuesMapper
              params:
                type: event-occurrence
            movie:
              class: londonDatabaseFilmsDataMapper

        -
          name: lisbon
          language: pt
          url: http://www.timeout.pt/
          days_ahead: 7
          from: <?php echo date( 'Y-m-d' ) . PHP_EOL ?>
          to:   <?php echo date( 'Y-m-d', strtotime( '+7 day' ) ) . PHP_EOL ?>
          type:
            poi:
              class: LisbonFeedVenuesMapper
            event:
              class: LondonDatabaseEventsAndVenuesMapper
            movie:
              class: LondonDatabaseEventsAndVenuesMapper
        -
          name: sydney
          type: [ poi, event, movie ]
        -
          name: moscow
          type: [ moscow_1, moscow_2, event ]
        -
          name: saint petersburg
          type: [ poi, event ]
        -
          name: almaty
          type: [ poi, event ]
        -
          name: russia
          type: [ movie ]
        -
          name: barcelona
          type: [ poi, event, movie ]
        -
          name: kuala lumpur
          type: [ poi, event, movie ]
        -
          name: mumbai
          type: [ poi, event, movie ]
        -
          name: delhi
          type: [ poi, event, movie ]
        -
          name: bangalore
          type: [ poi, event, movie ]
        -
          name: pune
          type: [ poi, event, movie ]
        -
          name: beijing-data-entry
          type: [ poi, event, movie ]
        -
          name: dubai
          type: [ bar, restaurant, poi, event, movie ]
        -
          name: abu dhabi
          type: [ bar, restaurant, poi, event, movie ]
        -
          name: istanbul
          type: [ poi, event, movie ]
        -
          name: singapore
          type: [ poi, event, movie ]
       

  export:
    cities:
        -
          name: singapore
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: ny
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: chicago
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: london
          type: [ poi, event, movie ]
          language: en-GB
          exportForNokia: true
        -
          name: lisbon
          type: [ poi, event, movie ]
          language: pt
          exportForNokia: true
        -
          name: sydney
          type: [ poi, event, movie ]
          language: en-AU
          exportForNokia: true
        -
          name: moscow
          type: [ poi, event, movie ]
          language: ru
          exportForNokia: true
        -
          name: saint petersburg
          type: [ poi, event, movie ]
          language: ru
          exportForNokia: true
        -
          name: almaty
          type: [ poi, event, movie ]
          language: ru
          exportForNokia: true
        -
          name: barcelona
          type: [ poi, event, movie ]
          language: ca
          exportForNokia: true
        -
          name: kuala lumpur
          type: [ poi, event, movie ]
          language: en-MY
          exportForNokia: true
        -
          name: mumbai
          type: [ poi, event, movie ]
          language: en-GB
          exportForNokia: true
        -
          name: delhi
          type: [ poi, event, movie ]
          language: en-GB
          exportForNokia: true
        -
          name: bangalore
          type: [ poi, event, movie ]
          language: en-GB
          exportForNokia: true
        -
          name: pune
          type: [ poi, event, movie ]
          language: en-GB
          exportForNokia: true
        -
          name: beijing
          type: [ poi, event, movie ]
          language: en-GB
          exportForNokia: true
        -
          name: dubai
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: abu dhabi
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: istanbul
          type: [ poi, event, movie ]
          language: tr
          exportForNokia: true



prod:
  #matches url: http://projectn.live/
  google_api_key : ABQIAAAA_FL2s5FUf4LMO_mUYDXUABSveoBGowI7nqh6kHEuOnD_thDOzhQRISkLudF55CGQjHRYPqfn429wzw

