# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

########## Example Import & Export / Post processing ##############
#
# import:
#   cities:
#     -
#       name: city name
#       type: [ poi, event, etc ]
#       postProcessing:
#         -
#           taskName: someName
#           namespace: projectn           # Default one is projectn, can be adjusted to any other namespace
#           params:
#             param1: value_for_param1
#             param2: 'Value for 2'
#   postProcessing:
#     -
#       taskName: someName
#       namespace: projectn
#       params:
#         param1: value_for_param1
#         param2: 'Value for 2'
#     -
#       taskName: cc
#       namespace: symfony
#       params: ~
# export
#   cities:
#     -
#       name: city name
#       type: [ poi, event, etc ]
#       language: en-US
#       exportForNokia: true
#       postProcessing:
#         -
#           taskName: someName
#           namespace: projectn
#           params:
#             param1: value_for_param1
#             param2: 'Value for 2'
#
#   postProcessing:
#     -
#       taskName: someName
#       namespace: projectn
#       params:
#         param1: value_for_param1
#         param2: 'Value for 2'
####################################################################
# Postprocessing can ve applied Globally ( Root element with cities in import / export)
# and can be applied to each individual cities. Global once will be executed ocne all the
# import or export finished and city once executed once city import or export finished.
##################### END ##########################################

# default values
all:
  #matches url: http://projectn.local/
  data_entry:
#.....................................................................
#     Data entry mappers are used for two different cases:
#     1 : importing from data entry database:
#         - in this case, onUpdateFindById is FALSE and vpid field in the input XML is interpreted as   vendor_event_id
#     2 : updating data_entry database
#         - steps for update :
#            * in projectn installation, we ran an export to create the XML files
#            * for some cities, the runner configuration has exportForDataEntry: true value, for those cities, prepareExportXMLsForDataEntryTask is called to create
#              new XML files with the modified IDs
#         - in data_entry instance the modified XML files are used to import the data back to data_entry database ,in this case, app_data_entry_onUpdateFindById is
#              TRUE and vpid field in the input XML is interpreted as the ID of the poi to be updated
#.......................................................................
    onUpdateFindById: false
  runner:
    tasks: [ import, export ]
  import:
    cities:
        -
          name: nyfix
          type: [ fixid ]
        -
          name: ny
          type: [ poi, event, movie ]
        -
          name: lisbon
          type: [ poi, event, movie ]
        -
          name: london
          type: [ poi-ev-mapper, poi-bars-pubs, poi-restaurant, poi-cinemas, event, event-occurrence, movie ]
        -
          name: sydney
          type: [ poi, event, movie ]
        -
          name: moscow
          type: [ moscow_poi_1, moscow_poi_2, moscow_poi_3, moscow_poi_4, event ]
        -
          name: saint petersburg
          type: [ poi, event ]
        -
          name: almaty
          type: [ poi, event ]
        -
          name: russia
          type: [ movie ]
        -
          name: barcelona
          type: [ poi, event, movie ]
        -
          name: kuala lumpur
          type: [ poi, event, movie ]
        -
          name: mumbai
          type: [ poi, event, movie ]
        -
          name: delhi
          type: [ poi, event ]
        -
          name: bangalore
          type: [ poi, event ]
        -
          name: pune
          type: [ poi, event ]
        -
          name: beijing-data-entry
          type: [ poi, event, movie ]
        -
          name: dubai
          type: [ bar, restaurant, poi, event, movie ]
        -
          name: abu dhabi
          type: [ bar, restaurant, poi, event, movie ]
        -
          name: bahrain
          type: [ bar, restaurant, poi, event, movie ]
        -
          name: doha
          type: [ bar, restaurant, poi, event, movie ]
        -
          name: istanbul
          type: [ poi_1, poi_2, event, movie ]
        -
          name: singapore
          type: [ poi, event, movie ]
        -
          name: hong kong
          type: [ poi, event, movie ]
        -
          name: istanbul_en
          type: [ poi, event, movie ]
        -
          name: shanghai_en
          type: [ poi, event, movie ]
        -
          name: shanghai_zh
          type: [ poi, event ]
        -
          name: beijing_zh
          type: [ poi, event, movie ]
        -
          name: melbourne
          type: [ poi, event, movie ]
        -
          name: amsterdam_data_entry
          type: [ poi, event, movie ]
        -
          name: beirut
          type: [ poi, event ]
        -
          name: bucharest
          type: [ poi, event, movie ]
        -
          name: omsk
          type: [ poi, event ]
        -
          name: krasnoyarsk
          type: [ poi, event ]
        -
          name: chicago
          type: [ poi-bc, poi-ed, poi, event_1, event_2, movie ]
          
  export:
    cities:
        -
          name: singapore
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: ny
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: chicago
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: london
          type: [ poi, event, movie ]
          language: en-GB
          exportForNokia: true
        -
          name: lisbon
          type: [ poi, event, movie ]
          language: pt
          exportForNokia: true
        -
          name: sydney
          type: [ poi, event, movie ]
          language: en-AU
          exportForNokia: true
        -
          name: moscow
          type: [ poi, event, movie ]
          language: ru
          exportForNokia: true
        -
          name: saint petersburg
          type: [ poi, event ]
          language: ru
          exportForNokia: true
          postProcessing:
            -
              taskName: duplicateExportedMovieFeed
              params:
                source: 'moscow'
                dest: 'saint petersburg'
                override: 'true'
        -
          name: almaty
          type: [ poi, event ]
          language: ru
          exportForNokia: true
          postProcessing:
            -
              taskName: duplicateExportedMovieFeed
              params:
                source: 'moscow'
                dest: 'almaty'
                override: 'true'
        -
          name: barcelona
          type: [ poi, event, movie ]
          language: ca
          exportForNokia: true
        -
          name: kuala lumpur
          type: [ poi, event, movie ]
          language: en-MY
          exportForNokia: true
        -
          name: mumbai
          type: [ poi, event, movie ]
          language: en-GB
          exportForNokia: true
        -
          name: delhi
          type: [ poi, event ]
          language: en-GB
          exportForNokia: true
          postProcessing:
            -
              taskName: duplicateExportedMovieFeed
              params:
                source: 'mumbai'
                dest: 'delhi'
                override: 'true'
        -
          name: bangalore
          type: [ poi, event ]
          language: en-GB
          exportForNokia: true
          postProcessing:
            -
              taskName: duplicateExportedMovieFeed
              params:
                source: 'mumbai'
                dest: 'bangalore'
                override: 'true'
        -
          name: pune
          type: [ poi, event ]
          language: en-GB
          exportForNokia: true
          postProcessing:
            -
              taskName: duplicateExportedMovieFeed
              params:
                source: 'mumbai'
                dest: 'pune'
                override: 'true'
        -
          name: beijing
          type: [ poi, event, movie ]
          language: en-GB
          exportForNokia: true
        -
          name: dubai
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: abu dhabi
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: bahrain
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: doha
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: istanbul
          type: [ poi, event, movie ]
          language: tr
          exportForNokia: true
        -
          name: hong kong
          type: [ poi, event, movie ]
          language: en-HK
          exportForNokia: true
        -
          name: istanbul_en
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: shanghai_en
          type: [ poi, event, movie ]
          language: en-GB
          exportForNokia: true
        -
          name: beijing_zh
          type: [ poi, event, movie ]
          language: zh-Hans
          exportForNokia: true
        -
          name: shanghai_zh
          type: [ poi, event ]
          language: zh-Hans
          exportForNokia: true
          postProcessing:
            -
              taskName: duplicateExportedMovieFeed
              params:
                source: 'beijing_zh'
                dest: 'shanghai_zh'
                override: 'true'
        -
          name: melbourne
          type: [ poi, event, movie ]
          language: en-AU
          exportForNokia: true
        -
          name: amsterdam
          type: [ poi, event, movie ]
          language: en
          exportForNokia: true
        -
          name: beirut
          type: [ poi, event, movie ]
          language: en-US
          exportForNokia: true
        -
          name: bucharest
          type: [ poi, event, movie ]
          language: ro
          exportForNokia: true
        -
          name: omsk
          type: [ poi, event ]
          language: ru
          exportForNokia: true
          postProcessing:
            -
              taskName: duplicateExportedMovieFeed
              params:
                source: 'moscow'
                dest: 'omsk'
                override: 'true'
        -
          name: krasnoyarsk
          type: [ poi, event ]
          language: ru
          exportForNokia: true
          postProcessing:
            -
              taskName: duplicateExportedMovieFeed
              params:
                source: 'moscow'
                dest: 'krasnoyarsk'
                override: 'true'
                
     # Export post processing tasks
    postProcessing: ~
prod:
  #matches url: http://projectn.live/
  google_api_key : ABQIAAAA_FL2s5FUf4LMO_mUYDXUABSveoBGowI7nqh6kHEuOnD_thDOzhQRISkLudF55CGQjHRYPqfn429wzw

