# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  #matches url: http://projectn.local/
  google_api_key : ABQIAAAAmYqAbSR2FhObG6Z6FL8nKhRU_WMEl20ocrt2ynGk4s1dqZjnGhSJ99yXGf0aEBbrPNUwBX1jiAA1gg
  data_entry:
    directory:
        projectn:            /var/vhosts/projectn_data_entry/export/
        projectn_data_entry: /var/vhosts/projectn/export/data_entry/
#.....................................................................
#     Data entry mappers are used for two different cases:
#     1 : importing from data entry database:
#         - in this case, onUpdateFindById is FALSE and vpid field in the input XML is interpreted as   vendor_event_id
#     2 : updating data_entry database
#         - steps for update :
#            * in projectn installation, we ran an export to create the XML files
#            * for some cities, the runner configuration has exportForDataEntry: true value, for those cities, prepareExportXMLsForDataEntryTask is called to create
#              new XML files with the modified IDs
#         - in data_entry instance the modified XML files are used to import the data back to data_entry database ,in this case, app_data_entry_onUpdateFindById is
#              TRUE and vpid field in the input XML is interpreted as the ID of the poi to be updated
#.......................................................................
    onUpdateFindById: false
  runner:
    order: [ import, export ]
  import:
    cities:
        -
          name: singapore
          type: [ poi-event, movie ]
        -
          name: ny
          type: [ poi-event, eating-drinking, bars-clubs, movie ]
        -
          name: chicago
          type: [ poi, poi-bc, poi-ed, event, movie]
        -
          name: london
          type: [ poi-ev-mapper, poi-bars-pubs, poi-restaurants, poi-cinemas ,event ,event-occurrence ,movie  ]
        -
          name: lisbon
          type: [ poi, event, movie ]
        -
          name: sydney
          type: [ poi, event, movie ]
        -
          name: moscow
          type: [ poi, event ]
        -
          name: saint petersburg
          type: [ poi, event ]
        -
          name: almaty
          type: [ poi, event ]
        -
          name: russia
          type: [ movie ]
        -
          name: barcelona
          type: [ poi, event, movie ]
        -
          name: kuala lumpur
          type: [ poi, event, movie ]
        -
          name: mumbai
          type: [ poi, event, movie ]
        -
          name: delhi
          type: [ poi, event, movie ]
        -
          name: bangalore
          type: [ poi, event, movie ]
        -
          name: pune
          type: [ poi, event, movie ]
        -
          name: beijing
          type: [ poi ]

  export:
    cities:
        -
          name: singapore
          type: [ poi, event, movie ]
          language: en-US
        -
          name: ny
          type: [ poi, event, movie ]
          language: en-US
        -
          name: chicago
          type: [ poi, event, movie ]
          language: en-US
        -
          name: london
          type: [ poi, event, movie ]
          language: en-GB
        -
          name: lisbon
          type: [ poi, event, movie ]
          language: pt
        -
          name: sydney
          type: [ poi, event, movie ]
          language: en-AU
        -
          name: moscow
          type: [ poi, event, movie ]
          language: ru
        -
          name: saint petersburg
          type: [ poi, event, movie ]
          language: ru
        -
          name: almaty
          type: [ poi, event, movie ]
          language: ru
        -
          name: barcelona
          type: [ poi, event, movie ]
          language: ca
        -
          name: kuala lumpur
          type: [ poi, event, movie ]
          language: en-MY
        -
          name: mumbai
          type: [ poi, event, movie ]
          language: en-GB
          exportForDataEntry: true
        -
          name: delhi
          type: [ poi, event, movie ]
          language: en-GB
          exportForDataEntry: true
        -
          name: bangalore
          type: [ poi, event, movie ]
          language: en-GB
          exportForDataEntry: true
        -
          name: pune
          type: [ poi, event, movie ]
          language: en-GB
          exportForDataEntry: true



prod:
  #matches url: http://projectn.live/
  google_api_key : ABQIAAAA_FL2s5FUf4LMO_mUYDXUABSveoBGowI7nqh6kHEuOnD_thDOzhQRISkLudF55CGQjHRYPqfn429wzw

