log_export_error:
  class: sfDoctrineRouteCollection
  options:
    model:                LogExportError
    module:               log_export_error
    prefix_path:          /log_export_error
    column:               id
    with_wildcard_routes: true

log_import_error:
  class: sfDoctrineRouteCollection
  options:
    model:                LogImportError
    module:               log_import_error
    prefix_path:          /log_import_error
    column:               id
    with_wildcard_routes: true

geo_white_list:
  class: sfDoctrineRouteCollection
  options:
    model:                GeoWhiteList
    module:               geo_white_list
    prefix_path:          /geo_white_list
    column:               id
    with_wildcard_routes: true

event:
  class: sfDoctrineRouteCollection
  options:
    model:                Event
    module:               event
    prefix_path:          /event
    column:               id
    with_wildcard_routes: true

movie:
  class: sfDoctrineRouteCollection
  options:
    model:                Movie
    module:               movie
    prefix_path:          /movie
    column:               id
    with_wildcard_routes: true

poi:
  class: sfDoctrineRouteCollection
  options:
    model:                Poi
    module:               poi
    prefix_path:          /poi
    column:               id
    with_wildcard_routes: true

vendor:
  class: sfDoctrineRouteCollection
  options:
    model:                Vendor
    module:               vendor
    prefix_path:          /vendor
    column:               id
    with_wildcard_routes: true

vendor_event_category:
  class: sfDoctrineRouteCollection
  options:
    model:                VendorEventCategory
    module:               vendor_event_category
    prefix_path:          /vendor_event_category
    column:               id
    with_wildcard_routes: true

vendor_poi_category:
  class: sfDoctrineRouteCollection
  options:
    model:                VendorPoiCategory
    module:               vendor_poi_category
    prefix_path:          /vendor_poi_category
    column:               id
    with_wildcard_routes: true

linking_poi_category_mapping:
  class: sfDoctrineRouteCollection
  options:
    model:                LinkingPoiCategoryMapping
    module:               linking_poi_category_mapping
    prefix_path:          /linking_poi_category_mapping
    column:               id
    with_wildcard_routes: true

poi_category:
  class: sfDoctrineRouteCollection
  options:
    model:                PoiCategory
    module:               poi_category
    prefix_path:          /poi_category
    column:               id
    with_wildcard_routes: true

geocode_ui:
  class: sfDoctrineRouteCollection
  options:
    model:                poi
    module:               geocode_ui
    prefix_path:          /geocode_ui
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
