generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Movie
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          movie
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        UnsolvableForm: { label: 'Unsolvable Movie?' }
      list:
        display: [=name, imdb_id]
        object_actions:
          _edit: ~
        actions: {}
        batch_actions: {}
      filter:
        class: MovieBackendFormFilter
        display:
          - id
          - hide_unsolvable
          - vendor_id
          - vendor_movie_id
          - name
          - imdb_id
          - plot
          - tag_line
          - review
          - movie_genres_list
          - url
          - director
          - writer
          - cast
          - age_rating
          - duration
          - country
          - language
          - aspect_ratio
          - sound_mix
          - company
          - rating
          - utf_offset
          - release_date
          - created_at
          - updated_at
      form:
        class: MovieBackendForm
        actions: { _list: ~, _save: ~ }
        display:
          Editable:
            - name
            - plot
            - tag_line
            - review
            - url
            - director
            - writer
            - cast
            - age_rating
            - release_date
            - duration
            - country
            - language
            - aspect_ratio
            - sound_mix
            - company
            - rating
            - utf_offset
            - imdb_id
            - movie_genres_list
            - UnsolvableForm
          Info:
            - id
            - vendor_id
            - vendor_movie_id
            - created_at
            - updated_at
      edit:    ~
      new:     ~
