import:
  
  bar:
    class:
      name: UAEFeedBarsMapper
      params:
        type: bar
        curl:
          classname: Curl
          src: http://www.timeoutabudhabi.com/nokia/bars

  restaurant:
    class:
      name: UAEFeedRestaurantsMapper
      params:
        type: restaurant
        curl:
          classname: Curl
          src: http://www.timeoutabudhabi.com/nokia/restaurants

  poi:
    class:
      name: UAEFeedPoiMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://www.timeoutabudhabi.com/nokia/latestevents
          xslt: uae_pois.xml

  event:
    class:
      name: UAEFeedEventsMapper
      params:
        type: event
        curl:
          classname: Curl
          src: http://www.timeoutabudhabi.com/nokia/latestevents
          xslt: uae_events.xml
          
  movie:
    class:
      name: UAEFeedFilmsMapper
      params:
        type: movie
        curl:
          classname: Curl
          src: http://www.timeoutabudhabi.com/customfeed/nokia/films
          xslt: uae_films.xml