import:
  
  poi:
    class:
      name: barcelonaVenuesMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://projectn-pro.gnuinepath.com/venues.xml

  movie:
    class:
      name: barcelonaMoviesMapper
      params:
        type: movie
        curl:
          classname: Curl
          src: http://projectn-pro.gnuinepath.com/movies.xml

  event:
    class:
      name: barcelonaEventsMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://projectn-pro.gnuinepath.com/events.xml
