import:
  poi:
    class:
      name: beijingZHFeedVenueMapper
      params:
        datasource:
          classname: curl
          src: "http://n.timeoutcn.com/Admin/Export/Venues.aspx"
          xmlsrc: http://n.timeoutcn.com/Admin/Export/Venues.xml
          username: "timeoutlondon"
          password: "aas9384jewt-0tkfd"