import:
  
  poi:
    class:
      name: bucharestVenueMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://127.0.0.1/bucharest-poi.xml



  event:
    class:
      name: bucharestEventMapper
      params:
        type: event
        curl:
          classname: Curl
          src: http://127.0.0.1/bucharest-event.xml
