import:
  
  poi:
    class:
      name: bucharestVenueMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://www.timeoutbucuresti.ro/project-n/venues.xml



  event:
    class:
      name: bucharestEventMapper
      params:
        type: event
        curl:
          classname: Curl
          src: http://www.timeoutbucuresti.ro/project-n/events.xml

  movie:
    class:
      name: bucharestMovieMapper
      params:
        type: movie
        curl:
          classname: Curl
          src: http://www.timeoutbucuresti.ro/project-n/movies.xml
