import:
  poi:
    class:
      name: ChicagoFeedPoiMapper
      params:
        type: poi
        ftp:
          classname: FTPClient
          ftp: ftp.timeoutchicago.com
          username: timeout
          password: y6fv2LS8
          file: 'toc_leo.xml'

  poi-bc:
    class:
      name: ChicagoFeedBCMapper
      params:
        type: bar_club
        ftp:
          classname: FTPClient
          ftp: ftp.timeoutchicago.com
          username: timeout
          password: y6fv2LS8
          file: 'toc_bc.xml'
          
  poi-ed:
    class:
      name: ChicagoFeedEDMapper
      params:
        type: bar_club
        ftp:
          classname: FTPClient
          ftp: ftp.timeoutchicago.com
          username: timeout
          password: y6fv2LS8
          file: 'toc_ed.xml'
#
  event_1:
    class:
      name: ChicagoFeedEventMapper
      params:
        type: poi
        ftp:
          classname: FTPClient
          ftp: ftp.timeoutchicago.com
          username: timeout
          password: y6fv2LS8
          file: 'toc_leo.xml'
        split:
          chunk: 2
          index: 1

  event_2:
    class:
      name: ChicagoFeedEventMapper
      params:
        type: poi
        ftp:
          classname: FTPClient
          ftp: ftp.timeoutchicago.com
          username: timeout
          password: y6fv2LS8
          file: 'toc_leo.xml'
        split:
          chunk: 2
          index: 2
          
  movie:
    class:
      name: londonDatabaseFilmsDataMapper
      params:
        query: "c.country_id = '931' AND  city_state LIKE '%IL'"
        review_type_id: 4
        database:
          dsn: 'mysql:dbname=film_convert;host=80.250.104.16'
          username: 'timeout'
          password: '65dali32'
