import:
  poi:
    class:
      name: HongKongFeedVenuesMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://www.timeout.com.hk/rss/venues/

  event:
    class:
      name: HongKongFeedEventsMapper
      params:
        type: event
        curl:
          classname: Curl
          src: http://www.timeout.com.hk/rss/events/

  movie:
    class:
      name: HongKongFeedMoviesMapper
      params:
        type: movie
        curl:
          classname: Curl
          src: http://www.timeout.com.hk/rss/movies/
