import:
  
  poi_1:
    class:
      name: istanbulVenueMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://www.timeoutistanbul.com/content/n_xml/venues.xml
        split:
          chunk: 2
          index: 1
  poi_2:
    class:
      name: istanbulVenueMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://www.timeoutistanbul.com/content/n_xml/venues.xml
        split:
          chunk: 2
          index: 2

  event:
    class:
      name: istanbulEventMapper
      params:
        type: event
        curl:
          classname: Curl
          src: http://www.timeoutistanbul.com/content/n_xml/events.xml

  movie:
    class:
      name: istanbulMovieMapper
      params:
        type: movie
        curl:
          classname: Curl
          src: http://www.timeoutistanbul.com/content/n_xml/movies.xml
