import:

  poi:
    class:
      name: RussiaFeedPlacesMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://www.timeout.ru/london/places_krasnoyarsk.xml
        phone:
          areacode: 391

  event:
    class:
      name: RussiaFeedEventsMapper
      params:
        type: event
        curl:
          classname: Curl
          src: http://www.timeout.ru/london/events_krasnoyarsk.xml
        phone:
          areacode: 391