import:
  poi:
    class:
      name: LisbonFeedVenuesMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://www.timeout.pt/xmlvenues.asp

  event:
    class:
      name: LisbonFeedListingsMapper
      params:
        type: event
        curl:
          classname: Curl
          src: http://www.timeout.pt/xmllist.asp
          pager:
            days_per_page: 7
            from: 'today'
            today: '+3 month'

  movie:
    class:
      name: LisbonFeedMoviesMapper
      params:
        type: movie
        curl:
          classname: Curl
          src: http://www.timeout.pt/xmlfilms.asp
