all:
  database:
    dsn: 'mysql:dbname=film_convert;host=80.250.104.16'
    username: 'timeout'
    password: '65dali32'

  cities:
    london_en_gb:  
      query: findByCountry
      params:
        country_id: 930
        review_type_id: 2
    ny_en_us:
      query: findByState
      params: 
        state: %NY
        review_type_id: 3
    chicago_en_us: 
      query: findByState
      params:
        state: %IL
        review_type_id: 4

test:
  #database:
  #  dsn: sqlite::memory:
  #  username: ~ 
  #  password: ~
  database:
    dsn: 'mysql:dbname=film_convert;host=80.250.104.16'
    username: 'timeout'
    password: '65dali32'

  cities:
    london_en_gb:  
      query: findByCountry
      params:
        country_id: 930
        review_type_id: 2
    ny_en_us:
      query: findByState
      params: 
        state: %NY
        review_type_id: 3
    chicago_en_us: 
      query: findByState
      params:
        state: %IL
        review_type_id: 4
