import:

  poi-ev-mapper:
    class:
      name: LondonDatabaseEventsAndVenuesMapper
      params:
        type: poi

  poi-bars-pubs:
    class:
      name: LondonAPIBarsAndPubsMapper
      params:
        datasource:
          classname: LondonAPICrawler
          url: http://api.timeout.com/v1/search.xml
          detailedurl: http://api.timeout.com/v1/getBar.xml
          apitype: Bars & pubs

  poi-restaurants:
    class:
      name: LondonAPIRestaurantsMapper
      params:
        datasource:
          classname: LondonAPICrawler
          url: http://api.timeout.com/v1/search.xml
          detailedurl: http://api.timeout.com/v1/getRestaurant.xml
          apitype: Restaurants & cafés

  poi-cinemas:
    class:
      name: LondonAPICinemasMapper
      params:
        datasource:
          classname: LondonAPICrawler
          url: http://api.timeout.com/v1/search.xml
          detailedurl: http://api.timeout.com/v1/getCinema.xml
          apitype: Cinemas

  event:
    class:
      name: LondonDatabaseEventsAndVenuesMapper
      params:
        type: event

  event-occurrence:
    class:
      name: LondonDatabaseEventsAndVenuesMapper
      params:
        type: event-occurrence

  movie:
    class:
      name: londonDatabaseFilmsDataMapper
      params:
        query: "c.country_id = '930'"
        review_type_id: 2
        database:
          dsn: 'mysql:dbname=film_convert;host=80.250.104.16'
          username: 'timeout'
          password: '65dali32'
