import:
  poi:
    class:
      name: australiaVenuesMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://au.timeout.com/melbourne/xmlapi/ixml/venues.xml

  event:
    class:
      name: australiaEventsMapper
      params:
        type: event
        curl:
          classname: Curl
          src: http://au.timeout.com/melbourne/xmlapi/ixml/events.xml

  movie:
    class:
      name: australiaMoviesMapper
      params:
        type: movie
        curl:
          classname: Curl
          src: http://au.timeout.com/melbourne/xmlapi/ixml/films.xml
