import:

  moscow_poi_1:
    class:
      name: RussiaFeedPlacesMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://www.timeout.ru/london/places_msk.xml
        split:
          chunk: 3
          index: 1
        phone:
          areacode: 495

  moscow_poi_2:
    class:
      name: RussiaFeedPlacesMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://www.timeout.ru/london/places_msk.xml
        split:
          chunk: 3
          index: 2
        phone:
          areacode: 495

  moscow_poi_3:
    class:
      name: RussiaFeedPlacesMapper
      params:
        type: poi
        curl:
          classname: Curl
          src: http://www.timeout.ru/london/places_msk.xml
        split:
          chunk: 3
          index: 3
        phone:
          areacode: 495

  event:
    class:
      name: RussiaFeedEventsMapper
      params:
        type: event
        curl:
          classname: Curl
          src: http://www.timeout.ru/london/events_msk.xml
        phone:
          areacode: 495