import:
  poi:
    class:
      name: nyEventsAndPoiMapper
      params:
        type: poi
        ftp:
          classname: FTPClient
          ftp: ftp.timeoutny.com
          username: london
          password: timeout
          dir: '/NOKIA/'
          file: 'tony_leo.xml'
          