import:

  poi:
    class:
      name: singaporePoiMapper
      params:
        type: poi
        datasource:
          classname: singaporeDataSource
          src: http://www.timeoutsingapore.com/xmlapi/venues/?section=index&full=&key=ffab6a24c60f562ecf705130a36c1d1e

  event:
    class:
      name: singaporeEventMapper
      params:
        type: event
        datasource:
          classname: singaporeDataSource
          src: http://www.timeoutsingapore.com/xmlapi/events/?section=index&full=&key=ffab6a24c60f562ecf705130a36c1d1e

  movie:
    class:
      name: singaporeMovieMapper
      params:
        type: movie
        datasource:
          classname: singaporeDataSource
          src: http://www.timeoutsingapore.com/xmlapi/movies/?section=index&full&key=ffab6a24c60f562ecf705130a36c1d1e
