<?php

/**
 * EventOccurrence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class EventOccurrence extends BaseEventOccurrence
{

//  public function preSave( $event )
//  {
//
//    echo "xxx";
//
//
//
//
//    if ( ! isset( $this[ 'vendor_event_id' ] ) )
//    {
//      echo "yyy";
//
//      $this->_generateVendorOccurrenceId();
//    }
//    else
//    {
//      echo "zzz";
//
//    }
//  }
//
//  public function preValidate( $event )
//  {
//    if ( ! isset( $this[ 'vendor_event_id' ] ) )
//    {
//
//
//      $this->_generateVendorOccurrenceId();
//    }
//  }

  /*
   * generates a vendor occurrence id
   *
   */
  public function generateVendorOccurrenceId( $eventId, $poiId, $startDate )
  {
    if ( !empty( $eventId ) && !empty( $poiId ) && !empty( $startDate ) )
    {
      $this[ 'vendor_event_occurrence_id' ] = $eventId . '_' . $poiId . '_' . date( 'YmdHis', strtotime( $startDate ) );
    }
    else
    {
      throw new Exception( 'one or more of the passed parameters($eventId, $poiId, $startDate) is empty' );
    }
  }

}
