<?php

/**
 * EventOccurrence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class EventOccurrence extends BaseEventOccurrence
{

  /*
   * generates a vendor occurrence id
   *
   */
  public function generateVendorEventOccurrenceId( $eventId, $poiId, $startDate )
  {
    if ( !empty( $eventId ) && !empty( $poiId ) && !empty( $startDate ) )
    {
      $this[ 'vendor_event_occurrence_id' ] = $eventId . '_' . $poiId . '_' . date( 'YmdHis', strtotime( $startDate ) );
    }
    else
    {
      throw new Exception( 'one or more of the passed parameters($eventId, $poiId, $startDate) is empty' );
    }
  }

}
