<?php

/**
 * EventOccurrence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class EventOccurrence extends BaseEventOccurrence
{
  /**
  * Attempts to fix and / or format fields, e.g. url
  */
  public function preSave( $event )
  {
    $this->cleanEmptyString();
  }

  public function cleanEmptyString()
  {
      // define Field type to check for empty string values
      $nullable_types = array( 'date', 'time', 'string' );

      // #874 loop through each field and make empty string value as null..
      // Doctrine v1.2.3 throws validation error when empty string found for date/time
      foreach( Doctrine::getTable( get_class( $this ) )->getColumns() as $column_name => $column_info )
      {
          if( in_array( $column_info['type'], $nullable_types ) && 
                  $column_info['notnull'] === false &&
                  stringTransform::mb_trim( $this[$column_name] ) == '' )
          {
              $this[ $column_name ] = null;
          }
      }
  }
}
