<?php

/**
 * LogImport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class LogImport extends BaseLogImport
{
    public function getCountFor( $model, $operations = array('received','insert','existing','failed','delete') )
    {
        $count = 0;
        
        foreach( $this['LogImportCount'] as $stat )
            if( $stat['model'] == $model && in_array( $stat['operation'], $operations ) )
                $count += $stat['count'];

        return $count;
    }

    public function getDate()
    {
        return substr( $this['created_at'], 0, 10 );
    }
}
