generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Event
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [ =name ]
        object_actions:
          _edit: ~
        actions: {}
        batch_actions: {}
      filter:
        class: EventBackendFormFilter
        display:
          - id
          - vendor_event_id
          - vendor_id
          - name
          - short_description
          - description
          - booking_url
          - url
          - price
          - rating
          - event_category_list
          - vendor_event_category_list
          - review_date
          - created_at
          - updated_at
      form:
        actions: { _list: ~, _save: ~ }
        display:
          Editable:
            - review_date
            - name
            - short_description
            - description
            - booking_url
            - url
            - price
            - rating
            - event_category_list
            - vendor_event_category_list
          Info:
            - vendor_id
            - vendor_event_id
            - created_at
            - updated_at
      edit:    ~
      new:     ~
