generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LogExportError
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          log_export_error
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        actions: {}
        object_actions: {}
        batch_actions: {}
        display:
          - created_at
          - model
          - record_id
          - log
          - log_export
      filter:
        display:
          - log_export_id
          - model
          - record_id
          - log
          - created_at
      form:    ~
      edit:    ~
      new:     ~
