<?php
require_once 'PHPUnit/Framework.php';
require_once dirname( __FILE__ ) . '/../../../../../test/bootstrap/unit.php';
require_once dirname( __FILE__ ) . '/../../../bootstrap.php';

/**
 * Test class for LisbonFeedVenuesMapper.
 * Generated by PHPUnit on 2010-01-29 at 10:32:04.
 */
class LisbonFeedVenuesMapperTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var LisbonFeedVenuesMapper
   */
  protected $object;

  /**
   * @var int
   */
  private $numVenuesInFixture = 6;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    ProjectN_Test_Unit_Factory::createDatabases();

    $vendor = ProjectN_Test_Unit_Factory::get( 'Vendor', array(
      'city' => 'Lisbon',
      'language' => 'pt'
      )
    );
    $vendor->save();
    $this->vendor = $vendor;
    
    $geoEncoder = $this->getMock('geoEncode', array( 'setAddress', 'getLongitude', 'getLatitude' ) );
    $geoEncoder->expects( $this->exactly( $this->numVenuesInFixture ) )
               ->method( 'setAddress' );

    $geoEncoder->expects( $this->exactly( $this->numVenuesInFixture ) )
               ->method( 'getLongitude' )
               ->will( $this->returnValue( 1.1 ) );

    $geoEncoder->expects( $this->exactly( $this->numVenuesInFixture ) )
               ->method( 'getLatitude' )
               ->will( $this->returnValue( 2.2 ) );

    $this->object = new LisbonFeedVenuesMapper(
      simplexml_load_file( TO_TEST_DATA_PATH . '/lisbon_venues.short.xml' ),
      $geoEncoder
    );
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    ProjectN_Test_Unit_Factory::destroyDatabases();
  }

  public function testMapVenues()
  {
    $importer = new Importer();
    $importer->addDataMapper( $this->object );
    $importer->run();
    
    $pois = Doctrine::getTable('Poi')->findAll();
    $this->assertEquals(  $this->numVenuesInFixture , $pois->count() );

    $poi = $pois[0];

    $this->assertEquals( 0,  $poi['vendor_poi_id'] );
    $this->assertEquals( 'PTR', $poi['local_language'] );
    $this->assertEquals( 'Igreja da Memória', $poi['poi_name'] );
    $this->assertEquals( '5 building name', $poi['house_no'] );
    $this->assertEquals( 'Lg da Memória, ', $poi['street'] );
    $this->assertEquals( 'Lisbon', $poi['city'] );
    $this->assertEquals( 'Portugal', $poi['country'] );
    $this->assertEquals( 'Lg da Memória, , Lg da Memória', $poi['additional_address_details'] );
    $this->assertEquals( '1.1', $poi['longitude'] );
    $this->assertEquals( '2.2', $poi['latitude'] );
    $this->assertEquals( 'test@test.com', $poi['email'] );
    $this->assertEquals( '07745674321', $poi['phone'] );
    $this->assertEquals( '07745671234', $poi['phone2'] );
    $this->assertEquals( 'Some category', $poi['vendor_category'] );
    $this->assertEquals( 'Tube: Saldanha, Bus: some bus, Rail: some rail', $poi['public_transport_links'] );
    $this->assertEquals( 'comedy price', $poi['price_information'] );
    $this->assertEquals( 'w23 fe', $poi['zips'] );
    $this->assertEquals( 'www.foo.com', $poi['url'] );
    $this->assertEquals( 'gay annonation, nightlife annotation', $poi['description'] );
    $this->assertEquals( 'abbreviation text', $poi['short_description'] );
    $this->assertEquals( '9:00', $poi['openingtimes'] );
    $this->assertEquals( '', $poi['review_date'] );
    $this->assertEquals( '', $poi['district'] );
    $this->assertEquals( '', $poi['fax'] );
    $this->assertEquals( '', $poi['keywords'] );
    $this->assertEquals( '', $poi['star_rating'] );
    $this->assertEquals( '', $poi['rating'] );
    $this->assertEquals( '', $poi['provider'] );
    $this->assertEquals( $this->vendor['id'], $poi['vendor_id'] );

    $this->assertGreaterThan( 0, $poi[ 'PoiProperty' ]->count() );
  }
}
?>
