generator:
  class: sfDoctrineGenerator
  param:
    model_class:           movie
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          movie
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        vendor_id: { attributes: { onchange: "document.forms[0].submit()" } }
        vendor_movie_id: { label: ID, help: Your unique identifier of the record }
        rating: { help: "Your rating of the Poi (0-5, 5 being the highest rating)" }
        utf_offset: { label: UTC Offset }
      list:
        display: [vendor_movie_id, name, imdb_id]
      filter:
        class: MovieDataEntryFormFilter
        display: [vendor_id, vendor_movie_id, name, imdb_id, plot, review, release_date, movie_genres_list]
      form:
        class: MovieDataEntryForm
        display:
          Editable:            
            - vendor_movie_id
            - name
            - plot
            - tag_line
            - review
            - url
            - director
            - writer
            - cast
            - age_rating
            - release_date
            - duration
            - country
            - language
            - aspect_ratio
            - sound_mix
            - company
            - rating
            - imdb_id
            - movie_genres_list
          Info:
            - vendor_id
            - utf_offset
            - created_at
            - updated_at
      edit:    ~
      new:     ~
