all:
  javascripts:
   - http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js
   - http://maps.google.com/maps/api/js?sensor=false
   - http://maps.google.com/maps/api/js?sensor=false&key=llkk
   
  stylesheets:    [ geocode_fix.css ]