<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SLLCategory', 'searchlight_london');

/**
 * BaseSLLCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_category_id
 * @property string $name
 * @property integer $status
 * @property string $name_url
 * @property string $tagline
 * @property date $last_listing_date
 * @property Doctrine_Collection $SLLVenueCategoryInformation
 * @property Doctrine_Collection $SLLEvent
 * @property Doctrine_Collection $SLLEventCategoryMapping
 * 
 * @method integer             getId()                          Returns the current record's "id" value
 * @method integer             getParentCategoryId()            Returns the current record's "parent_category_id" value
 * @method string              getName()                        Returns the current record's "name" value
 * @method integer             getStatus()                      Returns the current record's "status" value
 * @method string              getNameUrl()                     Returns the current record's "name_url" value
 * @method string              getTagline()                     Returns the current record's "tagline" value
 * @method date                getLastListingDate()             Returns the current record's "last_listing_date" value
 * @method Doctrine_Collection getSLLVenueCategoryInformation() Returns the current record's "SLLVenueCategoryInformation" collection
 * @method Doctrine_Collection getSLLEvent()                    Returns the current record's "SLLEvent" collection
 * @method Doctrine_Collection getSLLEventCategoryMapping()     Returns the current record's "SLLEventCategoryMapping" collection
 * @method SLLCategory         setId()                          Sets the current record's "id" value
 * @method SLLCategory         setParentCategoryId()            Sets the current record's "parent_category_id" value
 * @method SLLCategory         setName()                        Sets the current record's "name" value
 * @method SLLCategory         setStatus()                      Sets the current record's "status" value
 * @method SLLCategory         setNameUrl()                     Sets the current record's "name_url" value
 * @method SLLCategory         setTagline()                     Sets the current record's "tagline" value
 * @method SLLCategory         setLastListingDate()             Sets the current record's "last_listing_date" value
 * @method SLLCategory         setSLLVenueCategoryInformation() Sets the current record's "SLLVenueCategoryInformation" collection
 * @method SLLCategory         setSLLEvent()                    Sets the current record's "SLLEvent" collection
 * @method SLLCategory         setSLLEventCategoryMapping()     Sets the current record's "SLLEventCategoryMapping" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSLLCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('parent_category_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '0',
             'notnull' => true,
             'length' => '1',
             ));
        $this->hasColumn('name_url', 'string', 255, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('tagline', 'string', 2147483647, array(
             'type' => 'string',
             'length' => '2147483647',
             ));
        $this->hasColumn('last_listing_date', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SLLVenueCategoryInformation', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('SLLEvent', array(
             'local' => 'id',
             'foreign' => 'master_category_id'));

        $this->hasMany('SLLEventCategoryMapping', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $nestedset0 = new Doctrine_Template_NestedSet();
        $this->actAs($nestedset0);
    }
}