<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SLLEventCategoryMapping', 'searchlight_london');

/**
 * BaseSLLEventCategoryMapping
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $event_id
 * @property integer $annotation_behavior
 * @property string $annotation
 * @property integer $master_category_id
 * @property SLLCategory $SLLCategory
 * @property SLLEvent $SLLEvent
 * 
 * @method integer                 getCategoryId()          Returns the current record's "category_id" value
 * @method integer                 getEventId()             Returns the current record's "event_id" value
 * @method integer                 getAnnotationBehavior()  Returns the current record's "annotation_behavior" value
 * @method string                  getAnnotation()          Returns the current record's "annotation" value
 * @method integer                 getMasterCategoryId()    Returns the current record's "master_category_id" value
 * @method SLLCategory             getSLLCategory()         Returns the current record's "SLLCategory" value
 * @method SLLEvent                getSLLEvent()            Returns the current record's "SLLEvent" value
 * @method SLLEventCategoryMapping setCategoryId()          Sets the current record's "category_id" value
 * @method SLLEventCategoryMapping setEventId()             Sets the current record's "event_id" value
 * @method SLLEventCategoryMapping setAnnotationBehavior()  Sets the current record's "annotation_behavior" value
 * @method SLLEventCategoryMapping setAnnotation()          Sets the current record's "annotation" value
 * @method SLLEventCategoryMapping setMasterCategoryId()    Sets the current record's "master_category_id" value
 * @method SLLEventCategoryMapping setSLLCategory()         Sets the current record's "SLLCategory" value
 * @method SLLEventCategoryMapping setSLLEvent()            Sets the current record's "SLLEvent" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSLLEventCategoryMapping extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_category_mapping');
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('event_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('annotation_behavior', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'default' => '1',
             'length' => '1',
             ));
        $this->hasColumn('annotation', 'string', 2147483647, array(
             'type' => 'string',
             'length' => '2147483647',
             ));
        $this->hasColumn('master_category_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SLLCategory', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('SLLEvent', array(
             'local' => 'event_id',
             'foreign' => 'id'));
    }
}