<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SLLVenue', 'searchlight_london');

/**
 * BaseSLLVenue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $neighbourhood_id
 * @property string $name
 * @property string $address
 * @property string $postcode
 * @property decimal $latitude
 * @property decimal $longitude
 * @property integer $status
 * @property integer $source_id
 * @property integer $event_count
 * @property string $alt_name
 * @property string $building_name
 * @property string $travel
 * @property string $opening_times
 * @property string $url
 * @property string $phone
 * @property string $email
 * @property integer $image_id
 * @property string $source
 * @property string $annotation
 * @property Doctrine_Collection $SLLVenueCategoryInformation
 * @property Doctrine_Collection $SLLOccurrence
 * 
 * @method integer             getId()                          Returns the current record's "id" value
 * @method integer             getNeighbourhoodId()             Returns the current record's "neighbourhood_id" value
 * @method string              getName()                        Returns the current record's "name" value
 * @method string              getAddress()                     Returns the current record's "address" value
 * @method string              getPostcode()                    Returns the current record's "postcode" value
 * @method decimal             getLatitude()                    Returns the current record's "latitude" value
 * @method decimal             getLongitude()                   Returns the current record's "longitude" value
 * @method integer             getStatus()                      Returns the current record's "status" value
 * @method integer             getSourceId()                    Returns the current record's "source_id" value
 * @method integer             getEventCount()                  Returns the current record's "event_count" value
 * @method string              getAltName()                     Returns the current record's "alt_name" value
 * @method string              getBuildingName()                Returns the current record's "building_name" value
 * @method string              getTravel()                      Returns the current record's "travel" value
 * @method string              getOpeningTimes()                Returns the current record's "opening_times" value
 * @method string              getUrl()                         Returns the current record's "url" value
 * @method string              getPhone()                       Returns the current record's "phone" value
 * @method string              getEmail()                       Returns the current record's "email" value
 * @method integer             getImageId()                     Returns the current record's "image_id" value
 * @method string              getSource()                      Returns the current record's "source" value
 * @method string              getAnnotation()                  Returns the current record's "annotation" value
 * @method Doctrine_Collection getSLLVenueCategoryInformation() Returns the current record's "SLLVenueCategoryInformation" collection
 * @method Doctrine_Collection getSLLOccurrence()               Returns the current record's "SLLOccurrence" collection
 * @method SLLVenue            setId()                          Sets the current record's "id" value
 * @method SLLVenue            setNeighbourhoodId()             Sets the current record's "neighbourhood_id" value
 * @method SLLVenue            setName()                        Sets the current record's "name" value
 * @method SLLVenue            setAddress()                     Sets the current record's "address" value
 * @method SLLVenue            setPostcode()                    Sets the current record's "postcode" value
 * @method SLLVenue            setLatitude()                    Sets the current record's "latitude" value
 * @method SLLVenue            setLongitude()                   Sets the current record's "longitude" value
 * @method SLLVenue            setStatus()                      Sets the current record's "status" value
 * @method SLLVenue            setSourceId()                    Sets the current record's "source_id" value
 * @method SLLVenue            setEventCount()                  Sets the current record's "event_count" value
 * @method SLLVenue            setAltName()                     Sets the current record's "alt_name" value
 * @method SLLVenue            setBuildingName()                Sets the current record's "building_name" value
 * @method SLLVenue            setTravel()                      Sets the current record's "travel" value
 * @method SLLVenue            setOpeningTimes()                Sets the current record's "opening_times" value
 * @method SLLVenue            setUrl()                         Sets the current record's "url" value
 * @method SLLVenue            setPhone()                       Sets the current record's "phone" value
 * @method SLLVenue            setEmail()                       Sets the current record's "email" value
 * @method SLLVenue            setImageId()                     Sets the current record's "image_id" value
 * @method SLLVenue            setSource()                      Sets the current record's "source" value
 * @method SLLVenue            setAnnotation()                  Sets the current record's "annotation" value
 * @method SLLVenue            setSLLVenueCategoryInformation() Sets the current record's "SLLVenueCategoryInformation" collection
 * @method SLLVenue            setSLLOccurrence()               Sets the current record's "SLLOccurrence" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSLLVenue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('venue');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('neighbourhood_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('address', 'string', 2147483647, array(
             'type' => 'string',
             'length' => '2147483647',
             ));
        $this->hasColumn('postcode', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('latitude', 'decimal', 9, array(
             'type' => 'decimal',
             'notnull' => true,
             'scale' => false,
             'length' => '9',
             ));
        $this->hasColumn('longitude', 'decimal', 9, array(
             'type' => 'decimal',
             'notnull' => true,
             'scale' => false,
             'length' => '9',
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('source_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => 1,
             'length' => '4',
             ));
        $this->hasColumn('event_count', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('alt_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('building_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('travel', 'string', 2147483647, array(
             'type' => 'string',
             'length' => '2147483647',
             ));
        $this->hasColumn('opening_times', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('image_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('source', 'string', 15, array(
             'type' => 'string',
             'length' => '15',
             ));
        $this->hasColumn('annotation', 'string', 2147483647, array(
             'type' => 'string',
             'length' => '2147483647',
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SLLVenueCategoryInformation', array(
             'local' => 'id',
             'foreign' => 'venue_id'));

        $this->hasMany('SLLOccurrence', array(
             'local' => 'id',
             'foreign' => 'venue_id'));
    }
}