<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../test/bootstrap/unit.php';
require_once dirname(__FILE__).'/../../../bootstrap.php';

/**
 * Test class for EventOccurrence.
 * Generated by PHPUnit on 2010-01-26 at 13:20:53.
 */
class EventOccurrenceTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var Poi
   */
  protected $poi;

  /**
   * @var Event
   */
  protected $event;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    ProjectN_Test_Unit_Factory::createDatabases();

    //$this->poi = ProjectN_Test_Unit_Factory::add( 'poi' );
    //$this->event = ProjectN_Test_Unit_Factory::add( 'event' );
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    ProjectN_Test_Unit_Factory::destroyDatabases();
  }

  /*
   * testIfAutomaticIdGenerationWorks
   *
   * @todo create proper test
   */
  public function testIfAutomaticIdGenerationWorks()
  {

    //$eventOccurrenceObj = new EventOccurrence();



  }

}
?>
