<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../test/bootstrap/unit.php';
spl_autoload_register(array('Doctrine', 'autoload'));

$configuration = ProjectConfiguration::getApplicationConfiguration('frontend', 'test', true);
new sfDatabaseManager($configuration);


/**
 * Test class for importNy.
 * Generated by PHPUnit on 2010-01-07 at 12:14:28.
 *
 *
 * @author Clarence Lee <clarencelee@timeout.com>
 *
 *
 */
class vendorTest extends PHPUnit_Framework_TestCase {


  protected $object;

  private $vendor;


  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {

    try {
      $pDB = Doctrine_Manager::connection(new PDO('sqlite::memory:'));
      Doctrine::createTablesFromModels( dirname(__FILE__).'/../../../../../lib/model/doctrine');

      $this->vendor = new Vendor();
      $this->vendor->setCity('test');
      $this->vendor->setLanguage('english');
      $this->vendor->save();

    }
    catch(PDOException $e)
    {
      echo $e->getMessage();
    }


  }


  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {


    //Close DB connection
    Doctrine_Manager::getInstance()->closeConnection(Doctrine_Manager::connection());
  }

  /**
   * Test if getName() returns the concatenated string out of city_language
   *
   */
  public function testGetName()
  {

    $this->assertEquals( 'test_english', $this->vendor->getName() );

  }

  



}
?>
