<?php
/**
 *
 */
require_once 'PHPUnit/Framework.php';

require_once( dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine.php');
require_once( dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/doctrine/sfDoctrineRecord.class.php');
spl_autoload_register(array('Doctrine', 'autoload'));

//require_once dirname(__FILE__).'/../../../../lib/import/database.class.php';

/**
 * Test class for database.
 * Generated by PHPUnit on 2010-01-08 at 15:33:32.
 */
class databaseTest extends PHPUnit_Framework_TestCase {
  /**
   * @var database
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new database;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * Make sure a connection is present
   */
  public function testFactory()
  {
    //test for object
    $this->assertType('object', database::factory());
  }
}
?>
