<?php
require_once 'PHPUnit/Framework.php';
require_once dirname(__FILE__).'/../../../../test/bootstrap/unit.php';
require_once dirname( __FILE__ ).'/../../bootstrap.php';

/**
 * Test class for SoapLoader.
 * Generated by PHPUnit on 2010-01-22 at 17:27:16.
 */
class SoapLoaderTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var SoapLoader
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * Tests that load() calls the right SOAP function and returns the correct
   * data
   */
  public function testLoad()
  {
    $wsdl = 'http://192.9.200.204:8080/4DWSDL';
    $function = 'GetVenuesByCreatedDateRequest';
    $params = array();
    $soapCaller = new SoapLoader( $wsdl, $function, $params );
    
    $result = $soapCaller->load();
    $this->assertTrue( $result instanceof SimpleXMLElement );
  }
}
?>
