all: ~


prod:
  searchlight_london:
    class:                sfDoctrineDatabase
    param:
      dsn:                mysql://projectn:outtime99@192.9.215.250/searchlight_london
      attributes:
        use_native_enum:  true
  project_n:
    class:                sfDoctrineDatabase
    param:
      dsn:                mysql://root:outtime99@localhost/project_n
      attributes:
        use_native_enum:  true


dev:
  searchlight_london:
    class:                sfDoctrineDatabase
    param:
      dsn:                mysql://root:outtime99@localhost/searchlight_london
      attributes:
        use_native_enum:  true
      profiler: false

  project_n:
    class:                sfDoctrineDatabase
    param:
      dsn:                mysql://root:outtime99@localhost/project_n
      attributes:
        use_native_enum:  true
      profiler: false

test :
  searchlight_london:
    class:                sfDoctrineDatabase
    param:
      dsn:                sqlite::memory:
      attributes:
        use_native_enum:  true
        validate:         all
  project_n:
    class:                sfDoctrineDatabase
    param:
      dsn:                sqlite::memory:
      attributes:
        use_native_enum:  true
        validate:         all


test-functional :
  searchlight_london:
    class:                sfDoctrineDatabase
    param:
      dsn:                sqlite:%SF_DATA_DIR%/searchlight_london.db:
      attributes:
        use_native_enum:  true
        validate:         all

  project_n:
    class:                sfDoctrineDatabase
    param:
      dsn:               sqlite:%SF_DATA_DIR%/project_n.db:
      attributes:
        use_native_enum:  true
        validate:         all