all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=projectn'
      username: root
      password: Panties69



dev:
  n_local:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=projectn'
      username: root
      password: Panties69

test:
  n_local:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=projectn_test'
      username: projectntest
      password:  Panties69
