all:
  project_n:
    class:                sfDoctrineDatabase
    param:
      dsn:                mysql://root:outtime99@localhost/project_n
      attributes:
        use_native_enum:  true


prod:
  project_n:
    class:                sfDoctrineDatabase
    param:
      dsn:                mysql://root:outtime99@localhost/project_n_prod
      attributes:
        use_native_enum:  true
        

test:
  project_n:
    class:                sfDoctrineDatabase
    param:
      dsn:                sqlite::memory:
      attributes:
        use_native_enum:  true

