all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=projectn'
      username: root
      password: superpass

dev:
  n_local:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=projectn'
      username: root
      password: superpass

test:
  n_local:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=projectn'
      username: root
      password: superpass
