<?php
require_once 'PHPUnit/Framework.php';

require_once dirname( __FILE__ ).'/../../../bootstrap.php';
require_once dirname(__FILE__).'/../../../../../test/bootstrap/unit.php';
spl_autoload_register(array('Doctrine', 'autoload'));

/**
 * Test class for singaporeImport.
 * Generated by PHPUnit on 2010-01-28 at 13:53:13.
 */
class singaporeImportTest extends PHPUnit_Framework_TestCase {
  /**
   * @var singaporeImport
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {

   ProjectN_Test_Unit_Factory::createDatabases();

   Doctrine::loadData('data/fixtures');
   
   $vendorObj = Doctrine::getTable('Vendor')->getVendorByCityAndLanguage('singapore', 'en-GB');

   $dataXMLObject = simplexml_load_file( dirname(__FILE__).'/../../../data/singapore_weekly_events.xml' );

   /*$stubCurlImporter = $this->getMock( 'curlImporter' );
    * $stubCurlImporter->expects( $this->any() )
                      ->method( 'getXML' )
                      ->will( $this->returnValue( $dataXMLObject ) );*/

    
   $this->object = new singaporeImport( $dataXMLObject, $vendorObj );
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }


  public function testInsertCategoriesPoisEvents()
  {
    $this->assertTrue( $this->object->insertCategoriesPoisEvents() );
  }

  public function testFetchPoiAndPoiCategory()
  {
    $stubReturnXMLObject = simplexml_load_file( dirname(__FILE__).'/../../../data/singapore_event_detail.xml' );
    $stubCurlImporter = $this->getMock( 'curlImporter' );
    $stubCurlImporter->expects( $this->any() )
                      ->method( 'getXML' )
                      ->will( $this->returnValue( $stubReturnXMLObject ) );

    $this->assertTrue( $this->object->fetchPoiAndPoiCategory( 7766 ) );
  }

}
?>
