<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../test/bootstrap/unit.php';
require_once dirname(__FILE__).'/../../bootstrap.php';

/**
 * Test class for logExport.
 * Generated by PHPUnit on 2010-03-03 at 14:03:34.
 */
class logExportTest extends PHPUnit_Framework_TestCase {
    /**
     * @var logExport
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

        ProjectN_Test_Unit_Factory::createDatabases();
        
        $vendorObj = ProjectN_Test_Unit_Factory::get( 'Vendor' );
        $vendorObj->save();

        $this->object = new logExport( $vendorObj[ 'id' ], 'poi' );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        ProjectN_Test_Unit_Factory::destroyDatabases();
    }

    public function testAddItem()
    {
        $this->object->addItem( 1, 'some id');
        sleep(2);
        $this->object->addItem( 1, 'some id');

        $exportLogger = Doctrine::getTable( 'ExportLogger' )->findOneById( 1 );

        $this->assertGreaterThanOrEqual( strtotime( '00:00:02' ), strtotime( $exportLogger[ 'total_time' ] ) );
        $this->assertEquals( 2 , count( $exportLogger[ 'ExportLoggerItem' ] ) );
    }
}
?>
