<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addeventoccurrence extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('event_occurrence', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'vendor_event_occurrence_id' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 50,
             ),
             'booking_url' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 1024,
             ),
             'start_date' => 
             array(
              'type' => 'date',
              'notnull' => true,
              'length' => 25,
             ),
             'start_time' => 
             array(
              'type' => 'time',
              'notnull' => false,
              'length' => 25,
             ),
             'end_date' => 
             array(
              'type' => 'date',
              'notnull' => false,
              'length' => 25,
             ),
             'end_time' => 
             array(
              'type' => 'time',
              'notnull' => false,
              'length' => 25,
             ),
             'utc_offset' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 9,
             ),
             'event_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'poi_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'vendor_event_occurrence_id_index' => 
              array(
              'fields' => 
              array(
               0 => 'vendor_event_occurrence_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('event_occurrence');
    }
}