<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addlinkingvendorpoicategory extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('linking_vendor_poi_category', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'vendor_poi_category_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'poi_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('linking_vendor_poi_category');
    }
}