<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addeventimage extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('event_image', array(
             'item_id' => 
             array(
              'type' => 'integer',
              'unsigned' => 1,
              'autoincrement' => true,
              'primary' => true,
              'length' => 4,
             ),
             'item_type' => 
             array(
              'type' => 'string',
              'primary' => true,
              'length' => 255,
             ),
             'image_id' => 
             array(
              'type' => 'integer',
              'unsigned' => 1,
              'primary' => true,
              'length' => 4,
             ),
             'sort_index' => 
             array(
              'type' => 'integer',
              'unsigned' => 1,
              'primary' => true,
              'length' => 4,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'item_id',
              1 => 'item_type',
              2 => 'image_id',
              3 => 'sort_index',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('event_image');
    }
}