<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpoicategoryreference extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('poi_category_reference', array(
             'parent_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'child_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'parent_id',
              1 => 'child_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('poi_category_reference');
    }
}