<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addmovieproperty extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('movie_property', array(
             'id' => 
             array(
              'type' => 'integer',
              'autoincrement' => true,
              'primary' => true,
              'length' => 8,
             ),
             'lookup' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 50,
             ),
             'value' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 1024,
             ),
             'movie_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'lookup_index' => 
              array(
              'fields' => 
              array(
               0 => 'lookup',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('movie_property');
    }
}