<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addvenuecategoryinformation extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('venue_category_information', array(
             'category_id' => 
             array(
              'type' => 'integer',
              'unsigned' => 1,
              'primary' => true,
              'length' => 4,
             ),
             'venue_id' => 
             array(
              'type' => 'integer',
              'unsigned' => 1,
              'primary' => true,
              'length' => 4,
             ),
             'annotation' => 
             array(
              'type' => 'string',
              'length' => 2147483647,
             ),
             'price_export' => 
             array(
              'type' => 'string',
              'length' => 2147483647,
             ),
             'telephone_export' => 
             array(
              'type' => 'string',
              'length' => 2147483647,
             ),
             'times_export' => 
             array(
              'type' => 'string',
              'length' => 2147483647,
             ),
             'url_export' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'food_served' => 
             array(
              'type' => 'integer',
              'length' => 1,
             ),
             'free_venue' => 
             array(
              'type' => 'integer',
              'length' => 1,
             ),
             'late_night' => 
             array(
              'type' => 'integer',
              'length' => 1,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'category_id',
              1 => 'venue_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('venue_category_information');
    }
}