<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addusercontent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user_content', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'vendor_ucid' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 32,
             ),
             'comment_subject' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 512,
             ),
             'comment_body' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 65535,
             ),
             'user_rating' => 
             array(
              'type' => 'float',
              'notnull' => false,
              'length' => NULL,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'poi_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('user_content');
    }
}