<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adduser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'vendor_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'user_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 32,
             ),
             'user_reputation' => 
             array(
              'type' => 'integer',
              'notnull' => false,
              'length' => 1,
             ),
             'user_infomation' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'comments_relevance' => 
             array(
              'type' => 'float',
              'notnull' => false,
              'length' => NULL,
             ),
             'specialty' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 128,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('user');
    }
}