<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addrecordfieldoverridemovie extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('record_field_override_movie', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'record_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'field' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 50,
             ),
             'received_value' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => NULL,
             ),
             'edited_value' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => NULL,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 0,
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('record_field_override_movie');
    }
}