<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addimportloggerchange extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('import_logger_change', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'update',
              1 => 'delete',
              ),
              'notnull' => true,
              'length' => NULL,
             ),
             'log' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'import_logger_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('import_logger_change');
    }
}