<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addeventcategory extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('event_category', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 50,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'name_index' => 
              array(
              'fields' => 
              array(
               0 => 'name',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('event_category');
    }
}