generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LogImportError
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          log_import_error
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at: { date_format: dd/MM/yy }
      list:
        actions: {}
        object_actions: {}
        #object_actions:
        #  resolve:     ~
        #  error_info:     ~
        batch_actions: {}
        display:
          - created_at
          - model
          - message
          - log_import
          - _error_actions
      filter:
        display:
          #- log_import_id #don't enable it kills the screen
          - model
          - exception_class
          - trace
          - message
          - log
          - created_at
      form:    ~
      edit:    ~
      new:     ~
