# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  import:
    cities:
        -
          name: beijing
          type: [ poi ]
  export:
    cities:
        -
          name: mumbai
          type: [ poi, event, movie ]
          language: en-GB
          validation: false
        -
          name: delhi
          type: [ poi, event, movie ]
          language: en-GB
          validation: false
        -
          name: bangalore
          type: [ poi, event, movie ]
          language: en-GB
          validation: false
        -
          name: pune
          type: [ poi, event, movie ]
          language: en-GB
          validation: false
        -
          name: beijing
          type: [ poi ]
          language: en-GB
          validation: false

prod:
  sf_guard_plugin:
    # we manually specify this url as the default would point to port :8181
    # which is the port the app is listening to on our server (london varnish
    # points to)
    success_signin_url: http://www.timeout.com/projectn/data_entry.php
