generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Poi
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          poi_geo_white_list
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        showmarked: { label: 'Filter'}
      list:
        display: [ id, poi_name, latitude, longitude]
        object_actions:
          _edit: ~
        actions: {}
        batch_actions: {}
      filter:
        class: geoWhiteListFilter
        display: [vendor_id, showmarked, poi_name, street, latitude, longitude ]
      form:    ~
      edit:    ~
      new:     ~
