generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LinkingPoiCategoryMapping
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          linking_poi_category_mapping
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:            POI Category Mapping
        fields:
          poi_category_name:        { label: Our Category }
          vendor_poi_category_name: { label: Vendor Category }
        display:                    [vendor_name, vendor_poi_category_name, poi_category_name]
      filter:  ~
      form:
        fields:
          map_from_id:        { label: Our Category }
          map_to_id:          { label: Vendor Category }
        display:              [map_from_id, map_to_id, shizzle]
      edit:
        title:            "Map POI Category %%vendor_poi_category_name%% (%%vendor_name%%) to:"
        display:              [map_to_id]
      new:
        title:            New POI Category Mapping for %%vendor_name%%
        display:              [map_from_id, map_to_id]
