generator:
  class: sfDoctrineGenerator
  param:
    model_class:           event
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        vendor_id:                    { attributes: { onchange: "document.forms[0].submit()" } }
        vendor_event_id:              { label: ID, help: Your unique identifier of the record }
        rating:                       { help: "Your rating of the Poi (0-5, 5 being the highest rating)" }
        EventOccurrenceDataEntry:     { label: Occurrences }
        newEventOccurrenceDataEntry:  { label: New occurrence }
        EventMediaDataEntry:          { label: Images }
        newEventMediaDataEntry:       { label: New image }
      list:
        display: [ vendor_event_id, name ]
      filter:
        class: EventDataEntryFormFilter
        display: [ vendor_id, vendor_event_id, name, review_date, short_description, description ]
      form:
        class: EventDataEntryForm
        display:
          Editable:
            - vendor_event_id
            - name
            - review_date
            - short_description
            - description
            - booking_url
            - url
            - price
            - rating
            - vendor_event_category_list
            - EventOccurrence
            - newEventOccurrenceDataEntry
            - EventMedia
            - newEventMediaDataEntry
          Info:
            - vendor_id
            - created_at
            - updated_at
      edit:    ~
      new:     ~
